import { afterEach, describe, expect, it, vi } from 'vitest';
import { mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { ProjectResumeService, latestTurnSummary } from '../src/personal/project-resume';
import type { ProjectRpc } from '../src/personal/codex-project-client';
import type { GithubSource } from '../src/personal/project-sources';

const dirs: string[] = [];
afterEach(() => { for (const dir of dirs.splice(0)) rmSync(dir, { recursive: true, force: true }); });
function fixture() {
  const dir = mkdtempSync(join(tmpdir(), 'dailyhouse-projects-')); dirs.push(dir);
  const repoPath = join(dir, 'existing'); mkdirSync(repoPath); writeFileSync(join(repoPath, 'keep.txt'), 'original');
  let origin = ''; let initialized = false;
  const git = vi.fn(async (args: string[], cwd?: string) => { if (args[0] === 'init') { initialized = true; mkdirSync(join(cwd!, '.git'), { recursive: true }); } if (args[0] === 'rev-parse') { if (!initialized) throw Error(); return 'abc'; } if (args[0] === 'remote' && args[1] === 'get-url') return origin; if (args[0] === 'remote' && args[1] === 'add') origin = args[3]; return ''; });
  const rpc: ProjectRpc = { call: vi.fn(async (method: string, params: any) => { if (method === 'project/list') return { data: [{ id: 'old', name: 'Old', roots: [{ path: repoPath }], updatedAt: 1 }, { id: 'existing', name: 'Garden', roots: [{ path: repoPath }], updatedAt: 2 }] }; if (method === 'thread/list') return { data: params.projectId ? [] : [{ id: 'thread-1', name: 'Real task', preview: 'Last user context', cwd: repoPath, updatedAt: 1000 }] }; if (method === 'project/create') return { project: { id: 'created-project' } }; if (method === 'thread/start' || method === 'thread/resume') return { thread: { id: 'created-thread' } }; if (method === 'turn/start') return { turn: { id: 'first-turn' } }; if (method === 'thread/read') return { thread: { turns: [] } }; throw Error(method); }) as any, close: vi.fn() };
  const github: GithubSource = { login: vi.fn(async () => 'AlexShen-Oguri'), repos: vi.fn(async () => [{ name: 'Garden', url: 'https://github.com/AlexShen-Oguri/Garden', private: true }]), create: vi.fn(async name => ({ name, url: `https://github.com/AlexShen-Oguri/${name}`, private: true })) };
  const ideas = { handoffContext: vi.fn(() => ({ markdown: '# Entire idea\nInitial thought\nConversation\nFusion source', idea: { entries: [{ content: 'Full timeline' }] } })), linkExternalProject: vi.fn() };
  const file = join(dir, 'state.json');
  const service = new ProjectResumeService(file, ideas, { rpc, github, git, workspaceRoot: join(dir, 'new'), snapshot: async () => ({ status: 'ready', branch: 'main', changedFiles: 2, remote: 'https://github.com/AlexShen-Oguri/Garden', hasOrigin: true }) });
  return { dir, repoPath, service, rpc, github, git, ideas, file };
}
describe('actual project resume state', () => {
  it('allows history only for an active known project, never an arbitrary path or a removed project', async () => { const f = fixture(); await f.service.refresh(); await expect(f.service.history('C:/private/arbitrary-repository', {})).rejects.toMatchObject({ status: 404 }); expect((await f.service.history('existing', {})).status).toBe('not_repository'); f.service.remove('existing'); await expect(f.service.history('existing', {})).rejects.toMatchObject({ status: 404 }); });
  it('removes only the known leading ambient envelope before truncating the actual user request', () => { const summarize = (text: string) => latestTurnSummary({ items: [{ type: 'userMessage', content: [{ type: 'text', text }] }] })?.request; const request = '请继续完善项目续航。\n保留这些 <notes>我的内容</notes>。'; expect(summarize(`\n<in-app-browser-context source="ambient-ui-state">${'Browser metadata '.repeat(200)}</in-app-browser-context>\n\n## My request:\n${request}`)).toBe(request); expect(summarize(`## My request:\n${request}`)).toBe(request); for (const original of ['<in-app-browser-context source="my-example">Keep this</in-app-browser-context>', '```xml\n<in-app-browser-context source="ambient-ui-state">Quoted example</in-app-browser-context>\n```', '<send_user_message_question_reply>Keep the answer</send_user_message_question_reply>']) expect(summarize(original)).toBe(original); });
  it('rejects a stale purge dialog after restore and re-delete, even within the same millisecond', async () => { const f = fixture(); await f.service.refresh(); const clock = vi.spyOn(Date, 'now').mockReturnValue(Date.now()); try { f.service.remove('existing'); const stale = f.service.trash().items[0].deletedAt; f.service.restore({ ids: ['existing'] }); f.service.remove('existing'); const current = f.service.trash().items[0].deletedAt; expect(current).not.toBe(stale); expect(() => f.service.purge({ ids: ['existing'], confirm: true, deletedAt: { existing: stale } })).toThrow('已变化'); expect(f.service.trash().items).toHaveLength(1); expect(() => f.service.purge({ ids: ['existing'], confirm: true, deletedAt: {} })).toThrow('已变化'); f.service.purge({ ids: ['existing'], confirm: true, deletedAt: { existing: current } }); expect(f.service.trash().items).toHaveLength(0); } finally { clock.mockRestore(); } });
  it('extracts only actual user and assistant text from the latest turn, excluding tool outputs', () => { expect(latestTurnSummary({ startedAt: 123000, status: 'completed', items: [{ type: 'userMessage', content: [{ type: 'text', text: 'Latest request' }] }, { type: 'commandExecution', text: 'secret command output' }, { type: 'agentMessage', text: 'Verified latest work' }] })).toMatchObject({ request: 'Latest request', response: 'Verified latest work', status: 'completed' }); expect(latestTurnSummary({ items: [{ type: 'commandExecution', text: 'not a summary' }] })).toBeUndefined(); });
  it('deduplicates Codex roots, prioritizes newest registration and presents real Git and thread evidence', async () => { const f = fixture(); const state = await f.service.refresh(); expect(state.items).toHaveLength(1); expect(state.items[0]).toMatchObject({ id: 'existing', title: 'Garden', git: { changedFiles: 2 }, repo: { match: 'remote' }, threads: [{ title: 'Real task', preview: 'Last user context' }] }); expect(state.integrations.github.status).toBe('ready'); });
  it('remove, restore, purge never changes external repositories or Codex registry', async () => { const f = fixture(); await f.service.refresh(); f.service.remove('existing'); expect((await f.service.list()).items).toHaveLength(0); expect(f.service.trash().items).toHaveLength(1); f.service.restore({ ids: ['existing'] }); expect((await f.service.list()).items).toHaveLength(1); f.service.remove('existing'); expect(() => f.service.purge({ ids: ['existing'] })).toThrow(); f.service.purge({ ids: ['existing'], confirm: true, deletedAt: { existing: f.service.trash().items[0].deletedAt } }); vi.mocked(f.rpc.call).mockClear(); await f.service.refresh(); expect((await f.service.list()).items).toHaveLength(0); expect(f.service.trash().items).toHaveLength(0); expect(vi.mocked(f.rpc.call).mock.calls.map(c => c[0])).toEqual(['project/list']); expect(readFileSync(join(f.repoPath, 'keep.txt'), 'utf8')).toBe('original'); expect(f.git).not.toHaveBeenCalled(); expect(readFileSync(f.file, 'utf8')).not.toContain('Last user context'); });
  it('retains cached evidence with explicit offline status', async () => { const f = fixture(); await f.service.refresh(); vi.mocked(f.rpc.call).mockRejectedValue(Error('offline')); vi.mocked(f.github.repos).mockRejectedValue(Error('offline')); const state = await f.service.refresh(); expect(state.items).toHaveLength(1); expect(state.integrations.codex.status).toBe('error'); expect(state.integrations.github.status).toBe('error'); });
  it('gives each root a stable identity and hides only the selected root', async () => { const f = fixture(); const second = join(f.dir, 'second'); mkdirSync(second); const original = f.rpc.call; f.rpc.call = vi.fn(async (method, params) => method === 'project/list' ? { data: [{ id: 'multi', name: 'Multi', roots: [{ path: f.repoPath }, { path: second }], updatedAt: 1 }] } : original(method, params)) as any; const before = await f.service.refresh(); expect(new Set(before.items.map(p => p.id)).size).toBe(2); f.service.remove(before.items[0].id); const after = await f.service.refresh(); expect(after.items).toHaveLength(1); expect(after.items[0].id).toBe(before.items[1].id); f.service.purge({ ids: [before.items[0].id], confirm: true, deletedAt: { [before.items[0].id]: f.service.trash().items[0].deletedAt } }); expect((await f.service.list()).items).toHaveLength(1); });
  it('does not resurrect purged private previews during an in-flight refresh', async () => { const f = fixture(); await f.service.refresh(); let release!: () => void; const block = new Promise<void>(resolve => { release = resolve; }); const original = f.rpc.call; let entered!: () => void; const started = new Promise<void>(resolve => { entered = resolve; }); f.rpc.call = vi.fn(async (method, params) => { if (method === 'thread/list') { entered(); await block; } return original(method, params); }) as any; const refresh = f.service.refresh(); await started; f.service.remove('existing'); f.service.purge({ ids: ['existing'], confirm: true, deletedAt: { existing: f.service.trash().items[0].deletedAt } }); release(); await refresh; expect(readFileSync(f.file, 'utf8')).not.toContain('Last user context'); expect((await f.service.list()).items).toHaveLength(0); });
});
describe('confirmed idea launch', () => {
  it('validates confirmation, names, unsupported fields and protects existing local folders', () => { const f = fixture(); const body = { name: 'Idea', repoName: 'idea', confirm: true }; for (const bad of [{ ...body, confirm: false }, { ...body, repoName: '../escape' }, { ...body, repoName: 'CON' }, { ...body, repoName: 'idea.git' }, { ...body, path: f.dir }]) expect(() => f.service.launch('idea', bad)).toThrow(); mkdirSync(join(f.dir, 'new', 'idea'), { recursive: true }); expect(() => f.service.launch('idea', body)).toThrow('文件夹'); expect(f.ideas.handoffContext).toHaveBeenCalledTimes(1); expect(f.github.create).not.toHaveBeenCalled(); });
  it('copies full context locally, initializes private repo, registers real Codex project and starts one task', async () => { const f = fixture(); const first = f.service.launch('idea', { name: 'My idea', repoName: 'my-idea', confirm: true }); const repeated = f.service.launch('idea', { name: 'My idea', repoName: 'my-idea', confirm: true }); expect(first.operation.id).toBe(repeated.operation.id); await f.service.idle(); const operation = f.service.operation(first.operation.id).operation; expect(operation).toMatchObject({ status: 'ready', step: 'complete', codexProjectId: 'created-project', threadId: 'created-thread' }); expect(f.github.create).toHaveBeenCalledTimes(1); expect(vi.mocked(f.rpc.call).mock.calls.filter(c => c[0] === 'turn/start')).toHaveLength(1); expect(readFileSync(join(operation.path, '.dailyhouse', 'inspiration.md'), 'utf8')).toContain('Fusion source'); expect(readFileSync(join(operation.path, '.dailyhouse', 'inspiration.json'), 'utf8')).toContain('Full timeline'); expect(readFileSync(join(operation.path, '.gitignore'), 'utf8')).toContain('.dailyhouse/'); expect(f.git.mock.calls.find(c => c[0][0] === 'add')?.[0]).toEqual(['add', '--', 'README.md', '.gitignore', 'AGENTS.md']); expect(f.ideas.linkExternalProject).toHaveBeenCalledWith('idea', 'created-project'); expect(JSON.stringify(operation)).not.toContain('Full timeline'); });
  it('resumes after failed GitHub creation without rewriting files or duplicate project creation', async () => { const f = fixture(); vi.mocked(f.github.create).mockRejectedValueOnce(Error('offline')); const { operation } = f.service.launch('idea', { name: 'Idea', repoName: 'retry-idea', confirm: true }); await f.service.idle(); expect(f.service.operation(operation.id).operation).toMatchObject({ status: 'failed', step: 'github' }); f.service.retry(operation.id); await f.service.idle(); expect(f.service.operation(operation.id).operation.status).toBe('ready'); expect(f.git.mock.calls.filter(c => c[0][0] === 'init')).toHaveLength(1); expect(vi.mocked(f.rpc.call).mock.calls.filter(c => c[0] === 'project/create')).toHaveLength(1); });
  it('does not re-send a handoff with unknown delivery status', async () => { const f = fixture(); const original = f.rpc.call; f.rpc.call = vi.fn(async (method, params) => { if (method === 'turn/start') throw Error('timeout after possible send'); return original(method, params); }) as any; const { operation } = f.service.launch('idea', { name: 'Idea', repoName: 'ambiguous', confirm: true }); await f.service.idle(); f.service.retry(operation.id); await f.service.idle(); expect(f.service.operation(operation.id).operation.status).toBe('failed'); expect(f.service.operation(operation.id).operation.message).toContain('不会再次发送'); expect(vi.mocked(f.rpc.call).mock.calls.filter(c => c[0] === 'turn/start')).toHaveLength(1); });
  it('deleting a local handoff record preserves external files and prevents relaunch duplicates', async () => { const f = fixture(); const { operation } = f.service.launch('idea', { name: 'Idea', repoName: 'kept-project', confirm: true }); expect(() => f.service.removeOperation(operation.id, { confirm: true })).toThrow('正在交接'); await f.service.idle(); expect(() => f.service.removeOperation(operation.id, {})).toThrow(); f.service.removeOperation(operation.id, { confirm: true }); expect(f.service.launchForIdea('idea')).toMatchObject({ operation: null, removed: true }); expect(existsSync(join(operation.path, '.dailyhouse', 'inspiration.md'))).toBe(true); expect(readFileSync(f.file, 'utf8')).not.toContain('Full timeline'); expect(() => f.service.launch('idea', { name: 'Idea', repoName: 'another', confirm: true })).toThrow('避免重复'); expect(vi.mocked(f.rpc.call).mock.calls.some(c => c[0] === 'project/delete')).toBe(false); });
  it('failed preflight never creates a workspace or GitHub repository', async () => { const f = fixture(); vi.mocked(f.github.login).mockRejectedValue(Error('wrong account')); const { operation } = f.service.launch('idea', { name: 'Idea', repoName: 'no-files', confirm: true }); await f.service.idle(); expect(f.service.operation(operation.id).operation.status).toBe('failed'); expect(existsSync(operation.path)).toBe(false); expect(f.github.create).not.toHaveBeenCalled(); });
  it('loads the persisted thread before handing off a turn', async () => { const f = fixture(); const original = f.rpc.call; let loaded = false; f.rpc.call = vi.fn(async (method, params) => { if (method === 'thread/resume') loaded = true; if (method === 'turn/start' && !loaded) throw Error('thread not loaded'); return original(method, params); }) as any; const { operation } = f.service.launch('idea', { name: 'Idea', repoName: 'resume', confirm: true }); await f.service.idle(); expect(f.service.operation(operation.id).operation.status).toBe('ready'); const methods = vi.mocked(f.rpc.call).mock.calls.map(c => c[0]); expect(methods.indexOf('thread/resume')).toBeLessThan(methods.indexOf('turn/start')); });
});
