import { describe, expect, it, vi } from 'vitest';
import { LocalGithubSource, githubRemote, matchGithubRepo } from '../src/personal/project-sources';

const owner = 'AlexShen-Oguri';
describe('GitHub association', () => {
  it('normalizes supported remotes only for the configured owner', () => { expect(githubRemote(`git@github.com:${owner}/Repo.git`)).toBe(`https://github.com/${owner}/Repo`); expect(githubRemote(`https://github.com/${owner}/Repo.git`)).toBe(`https://github.com/${owner}/Repo`); for (const remote of ['https://token@github.com/AlexShen-Oguri/Repo', 'https://evil.com/AlexShen-Oguri/Repo', 'https://github.com/another/Repo']) expect(githubRemote(remote)).toBeUndefined(); });
  it('never lets a same-name repository override a different origin', () => { const repos = [{ name: 'Repo', url: `https://github.com/${owner}/Repo`, private: true }]; expect(matchGithubRepo('Repo', '/Repo', { status: 'ready', hasOrigin: true, remote: `https://github.com/${owner}/Different` }, repos)).toBeUndefined(); expect(matchGithubRepo('Repo', '/Repo', { status: 'ready', hasOrigin: true }, repos)).toBeUndefined(); expect(matchGithubRepo('Repo', '/Repo', { status: 'not_repository' }, repos)?.match).toBe('name'); });
  it('uses credentials only for fixed GitHub API endpoints and redacts failures', async () => { const git = vi.fn(async () => 'username=someone\npassword=TOP_SECRET\n'); const fetcher = vi.fn(async (url: any, options: any) => { expect(String(url).startsWith('https://api.github.com/')).toBe(true); expect(options.redirect).toBe('error'); expect(options.headers.Authorization).toBe('Bearer TOP_SECRET'); return new Response(JSON.stringify({ login: owner }), { status: 200 }); }); const source = new LocalGithubSource(git, fetcher as typeof fetch); expect(await source.login()).toBe(owner); fetcher.mockImplementationOnce(async () => new Response('TOP_SECRET', { status: 403 })); await expect(source.login()).rejects.toThrow('权限'); expect(git.mock.calls[0]?.[0]).toEqual(['credential', 'fill']); });
  it('rejects account mismatch before writes', async () => { const source = new LocalGithubSource(async () => 'password=secret\n', (async () => new Response(JSON.stringify({ login: 'another' }))) as typeof fetch); await expect(source.create('Repo', 'op')).rejects.toThrow(owner); });
  it('uses a private marked repository and recovers idempotently without adopting existing unrelated repositories', async () => { let exists = false; const requests: any[] = []; const api = vi.fn(async (url: any, options: any) => { requests.push({ url, method: options.method, body: options.body }); const row = { name: 'Repo', private: true, owner: { login: owner }, description: 'DailyHouse idea launch op' }; if (url.endsWith('/user')) return Response.json({ login: owner }); if (options.method === 'POST') { exists = true; return Response.json(row); } return exists ? Response.json(row) : new Response('{}', { status: 404 }); }); const source = new LocalGithubSource(async () => 'password=secret\n', api as typeof fetch); await source.create('Repo', 'op'); await source.create('Repo', 'op'); expect(requests.filter(r => r.method === 'POST')).toHaveLength(1); expect(JSON.parse(requests.find(r => r.method === 'POST').body)).toMatchObject({ name: 'Repo', private: true, auto_init: false }); await expect(source.create('Repo', 'other-operation')).rejects.toThrow('已存在'); });
});
