import { useEffect, useRef, useState, type FormEvent } from 'react';
import { Link } from 'react-router-dom';
import { request, dateLabel } from './api';
import { usePreferences } from './Preferences';
import { Notice } from './shared';
import { brainstorm, type Bubble, type Direction, type InspirationDraft, type InspirationState, type Project } from './inspiration-model';
import ProjectFields, { PlanListField, type ProjectPlan } from './ProjectFields';

export default function InspirationExplore({ bubble, ai, onChanged }: { bubble: Bubble; ai: InspirationState['ai']; onChanged: () => Promise<void> }) {
  const { t, language, locale } = usePreferences(); const [purpose, setPurpose] = useState<InspirationDraft['purpose']>('directions'); const [context, setContext] = useState(''); const [excerpt, setExcerpt] = useState(() => bubble.body.slice(0, 3500)); const [sources, setSources] = useState<string[]>([]);
  const [generating, setGenerating] = useState(false); const [busy, setBusy] = useState(''); const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [activeDraft, setActiveDraft] = useState<string | null>(null); const [editing, setEditing] = useState<{ id: string; index: number; direction: Direction } | null>(null); const [plan, setPlan] = useState<ProjectPlan | null>(null); const [planDraft, setPlanDraft] = useState<string>(); const [removeDraft, setRemoveDraft] = useState<string>(); const [undoConfirm, setUndoConfirm] = useState(false);
  const controller = useRef<AbortController | null>(null); const mounted = useRef(true); const feedback = useRef<HTMLDivElement>(null);
  useEffect(() => { mounted.current = true; return () => { mounted.current = false; controller.current?.abort(); }; }, []);
  const orderedDrafts = [...bubble.drafts].sort((a, b) => b.createdAt.localeCompare(a.createdAt));
  const draft = bubble.drafts.find(item => item.id === activeDraft) ?? orderedDrafts[0];
  const locked = generating || !!busy;
  const inputLength = JSON.stringify({ title: bubble.title, body: excerpt, sources: bubble.sources.filter(source => sources.includes(source.id)).map(({ title, body }) => ({ title, body })), purpose, context, language }).length;
  const contextTooLong = inputLength > 5000;
  async function generate(event: FormEvent) {
    event.preventDefault(); if (locked || contextTooLong || !excerpt.trim()) return; const abort = new AbortController(); controller.current = abort; setGenerating(true); setError(''); setMessage('');
    try { const result = await brainstorm(bubble.id, { purpose, context, ideaExcerpt: excerpt, includeSourceIds: sources, language, expectedRevision: bubble.revision }, abort.signal); if (!mounted.current || abort.signal.aborted) return; await onChanged(); setActiveDraft(result.id); setMessage(t('三个方向已保存为草稿。你可以改写，再决定要不要做。', 'Three directions saved as drafts. Edit them before deciding what to make.')); }
    catch (err) { if (!mounted.current) return; if (abort.signal.aborted) setMessage(t('已取消本次发散。输入内容仍保留。', 'Exploration cancelled. Your inputs are still here.')); else setError(err instanceof TypeError ? t('模型服务暂时没有响应。请重试，输入已保留。', 'The model service did not respond. Your input is kept; try again.') : (err as Error).message); }
    finally { if (mounted.current) { setGenerating(false); controller.current = null; } }
  }
  async function action(key: string, work: () => Promise<unknown>, success: string) { if (locked) return; setBusy(key); setError(''); setMessage(''); try { await work(); await onChanged(); setMessage(success); } catch (err) { setError((err as Error).message); } finally { setBusy(''); } }
  function startProject(direction?: Direction, draftId?: string) { setPlan({ title: direction?.title ?? bubble.title, goal: direction?.goal ?? bubble.body.slice(0, 2000), mvp: direction?.mvp ?? [], acceptance: direction?.acceptance ?? [], nextStep: direction?.firstStep ?? '' }); setPlanDraft(draftId); setEditing(null); }
  async function createProject(event: FormEvent) { event.preventDefault(); if (!plan) return; await action('project', async () => { const result = await request<{ project: Project; created: boolean }>(`/inspiration/${bubble.id}/project`, 'POST', { ...plan, ...(planDraft ? { draftId: planDraft } : {}) }); setPlan(null); setMessage(result.created ? t('项目已建立，第一步尚未加入待办。', 'Project created. Add its first step to tasks when ready.') : t('这颗气泡已有关联项目，已保留原项目。', 'This bubble already has a project; the existing project was kept.')); }, t('项目已关联。可以在项目库继续推进。', 'Project linked. Continue in your project library.')); }
  return <section className="idea-explore" aria-labelledby="idea-explore-title"><div className="idea-section-title"><h3 id="idea-explore-title">{t('让想法长出方向', 'Give this idea a direction')}</h3><span className="idea-meta">{t('本机开源模型', 'Local open model')}</span></div>
    <p className="idea-help">{t('只发送你在这里确认的内容。模型的建议会另存为草稿，不改动原灵感。', 'Only the content you review here is sent. Suggestions are saved separately and never overwrite the idea.')}</p>
    {!ai.configured && <Notice>{ai.message || t('本机模型尚未就绪。启动 Ollama 并准备好指定模型后刷新。', 'The local model is not ready. Start Ollama, prepare the selected model, then refresh.')} <button className="pw-text-button" disabled={locked} onClick={() => void onChanged()}>{t('重新检查模型', 'Check model again')}</button></Notice>}
    <form onSubmit={generate}><fieldset className="idea-fields" disabled={locked}><label>{t('这次想探索什么', 'What would you like to explore?')}<select value={purpose} onChange={e => setPurpose(e.target.value as typeof purpose)}><option value="directions">{t('找不同方向', 'Find different directions')}</option><option value="mvp">{t('缩成最小实验', 'Find the smallest experiment')}</option><option value="feasibility">{t('检查可行性', 'Check feasibility')}</option></select></label><label>{t('补充约束（选填）', 'Constraints (optional)')}<textarea value={context} onChange={e => setContext(e.target.value)} maxLength={3000} rows={3} placeholder={t('例如：周末做完、会 React、送给朋友、不需要登录…', 'For example: one weekend, I know React, a gift for a friend, no sign-in…')}/></label></fieldset>
      <details className="idea-send-preview" open><summary>{t('将发送给模型的内容', 'Content sent to the model')}</summary><p><strong>{bubble.title}</strong></p><label>{t('本次发送的灵感摘录', 'Idea excerpt for this request')}<textarea value={excerpt} onChange={e => setExcerpt(e.target.value)} maxLength={3500} rows={5} disabled={locked} required/></label><p className="idea-meta">{t('可以删减本次摘录，不会改写原时间线。', 'Trim this excerpt without changing the original timeline.')}</p>{bubble.sources.length > 0 && <fieldset disabled={locked}><legend>{t('可选：同时发送这些来源快照', 'Optional: include these source snapshots')}</legend>{bubble.sources.map(source => <label className="idea-check" key={source.id}><input type="checkbox" checked={sources.includes(source.id)} onChange={e => setSources(previous => e.target.checked ? [...previous, source.id] : previous.filter(id => id !== source.id))}/><span><strong>{source.title}</strong>{source.body && <small>{source.body}</small>}</span></label>)}</fieldset>}<p className="idea-meta">{ai.model} · {t('不会读取整个灵感库、文件或历史对话。', 'No access to the rest of your ideas, files or conversations.')}</p></details>
      {contextTooLong && <Notice>{t('本次内容超过模型上下文上限，请缩短摘录、补充约束，或减少勾选来源。', 'This request exceeds the model context limit. Shorten the excerpt or constraints, or select fewer sources.')}</Notice>}<div className="idea-actions"><button className="pw-button primary" disabled={locked || !ai.configured || contextTooLong || !excerpt.trim()}>{generating ? t('正在思考…', 'Exploring…') : t('发送并生成方向', 'Send and explore')}</button>{generating && <button className="pw-button" type="button" onClick={() => controller.current?.abort()}>{t('取消生成', 'Cancel generation')}</button>}</div>
    </form>
    <div ref={feedback} aria-live="polite">{error && <Notice error>{error}</Notice>}{message && <Notice>{message}</Notice>}</div>
    {bubble.drafts.length > 0 && <div className="idea-drafts"><div className="idea-section-title"><h3>{t('发散草稿', 'Exploration drafts')}</h3><label><span className="pw-sr-only">{t('选择草稿版本', 'Choose draft version')}</span><select value={draft?.id ?? ''} disabled={locked || !!editing} onChange={e => { setActiveDraft(e.target.value); setRemoveDraft(undefined); }} >{orderedDrafts.map(item => <option value={item.id} key={item.id}>{dateLabel(item.createdAt, locale)}</option>)}</select></label></div>
      {draft?.directions.map((direction, index) => <article className="idea-direction" key={`${draft.id}-${index}`}><h4>{direction.title}</h4><p>{direction.goal}</p><dl><dt>{t('最小版本', 'Smallest version')}</dt><dd><ul>{direction.mvp.map((line, i) => <li key={i}>{line}</li>)}</ul></dd><dt>{t('待验证的假设与风险', 'Assumptions and risks')}</dt><dd><ul>{[...direction.assumptions, ...direction.risks].map((line, i) => <li key={i}>{line}</li>)}</ul></dd><dt>{t('如何验收', 'How to check it works')}</dt><dd><ul>{direction.acceptance.map((line, i) => <li key={i}>{line}</li>)}</ul></dd><dt>{t('第一步', 'First step')}</dt><dd>{direction.firstStep}</dd></dl><div className="idea-actions"><button className="pw-button" disabled={locked} onClick={() => setEditing({ id: draft.id, index, direction: structuredClone(direction) })}>{t('改写方向', 'Edit direction')}</button>{!bubble.projectId && <button className="pw-button primary" disabled={locked} onClick={() => startProject(direction, draft.id)}>{t('用这个方向立项', 'Plan this project')}</button>}</div></article>)}
      {draft && <div className="idea-actions"><button className="pw-text-button idea-danger" disabled={locked} onClick={() => setRemoveDraft(draft.id)}>{t('移除这次草稿', 'Remove this draft')}</button></div>}{removeDraft && <div className="idea-confirm" role="group" aria-label={t('确认移除草稿', 'Confirm draft removal')}><p>{t('这次模型草稿将被删除；原始气泡和已经建立的项目保留。', 'This model draft will be deleted. Your original idea and existing projects are kept.')}</p><div className="idea-actions"><button className="pw-button" disabled={locked} onClick={() => setRemoveDraft(undefined)}>{t('取消', 'Cancel')}</button><button className="pw-button" disabled={locked} onClick={() => void action('remove-draft', async () => { await request(`/inspiration/${bubble.id}/drafts/${removeDraft}`, 'DELETE'); setRemoveDraft(undefined); }, t('草稿已移除。', 'Draft removed.'))}>{t('确认移除草稿', 'Remove draft')}</button></div></div>}
    </div>}
    {editing && <form className="idea-inline-editor" onSubmit={event => { event.preventDefault(); void action('draft-save', async () => { const previous = bubble.drafts.find(item => item.id === editing.id); if (!previous) return; const directions = previous.directions.map((direction, index) => index === editing.index ? editing.direction : direction); await request(`/inspiration/${bubble.id}/drafts/${editing.id}`, 'PATCH', { directions, expectedUpdatedAt: previous.updatedAt }); setEditing(null); }, t('方向已更新。', 'Direction updated.')); }}><h3>{t('改写这个方向', 'Edit this direction')}</h3><ProjectFields value={{ ...editing.direction, nextStep: editing.direction.firstStep }} disabled={locked} goalLimit={1000} onChange={value => setEditing({ ...editing, direction: { ...editing.direction, title: value.title, goal: value.goal, mvp: value.mvp, acceptance: value.acceptance, firstStep: value.nextStep } })}/><fieldset className="idea-fields" disabled={locked}><PlanListField label={t('假设（每行一项）', 'Assumptions (one per line)')} value={editing.direction.assumptions} onChange={assumptions => setEditing({ ...editing, direction: { ...editing.direction, assumptions } })}/><PlanListField label={t('风险（每行一项）', 'Risks (one per line)')} value={editing.direction.risks} onChange={risks => setEditing({ ...editing, direction: { ...editing.direction, risks } })}/></fieldset><div className="idea-actions"><button className="pw-button primary" disabled={locked}>{t('保存方向', 'Save direction')}</button><button className="pw-button" type="button" disabled={locked} onClick={() => setEditing(null)}>{t('取消', 'Cancel')}</button></div></form>}
    <div className="idea-project-start">{bubble.projectId ? <><Link className="pw-button primary" to={`/projects?project=${encodeURIComponent(bubble.projectId)}`}>{t('打开关联项目', 'Open linked project')}</Link><button className="pw-text-button" disabled={locked} onClick={() => setUndoConfirm(true)}>{t('撤销本次立项', 'Undo project creation')}</button></> : !plan && <button className="pw-button" disabled={locked} onClick={() => startProject()}>{t('我已有方向，直接立项', 'I have a direction — plan a project')}</button>}</div>
    {undoConfirm && <div className="idea-confirm"><p>{t('仅撤回尚未编辑、尚未生成待办的项目；项目进入回收站，原灵感保留。若已有后续工作，会保留项目并说明冲突。', 'Only an unedited project with no task can be undone. It moves to the recycle bin while the idea stays. Later work is protected and reported as a conflict.')}</p><div className="idea-actions"><button className="pw-button" disabled={locked} onClick={() => setUndoConfirm(false)}>{t('取消', 'Cancel')}</button><button className="pw-button" disabled={locked} onClick={() => void action('undo', async () => { await request(`/inspiration/${bubble.id}/project/undo`, 'POST'); setUndoConfirm(false); }, t('立项已撤回，项目记录可从回收站恢复。', 'Project creation undone. The project can be restored from the recycle bin.'))}>{t('确认撤销立项', 'Undo project creation')}</button></div></div>}
    {plan && <form className="idea-inline-editor" onSubmit={createProject}><h3>{t('确认这次想做的项目', 'Review the project you want to make')}</h3><p className="idea-help">{t('这里的内容会保存为项目记录。不会创建代码仓库，也不会自动添加待办。', 'This saves a project record. It does not create a code repository or add a task automatically.')}</p><ProjectFields value={plan} onChange={setPlan} disabled={locked}/><div className="idea-actions"><button className="pw-button primary" disabled={locked || !plan.title.trim() || !plan.goal.trim()}>{busy === 'project' ? t('建立中…', 'Creating…') : t('确认立项', 'Create project')}</button><button className="pw-button" type="button" disabled={locked} onClick={() => setPlan(null)}>{t('先不立项', 'Keep exploring')}</button></div></form>}
  </section>;
}
