import { useCallback, useEffect, useRef, useState, type FormEvent } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { request, dateLabel } from './api';
import { usePreferences } from './Preferences';
import { Empty, Notice } from './shared';
import type { Bubble, InspirationState, TrashRecord } from './inspiration-model';
import '../styles/inspiration.css';

export default function InspirationBoard({ visibleIds, mode, search = '', refreshKey = '', onChanged }: { visibleIds: string[]; mode: 'garden' | 'trash'; search?: string; refreshKey?: string; onChanged: () => Promise<void> }) {
  const { t, language, locale } = usePreferences(); const navigate = useNavigate(); const [items, setItems] = useState<Bubble[]>([]); const [trash, setTrash] = useState<TrashRecord<Bubble>[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false); const [selected, setSelected] = useState<string[]>([]); const [merge, setMerge] = useState(false); const [title, setTitle] = useState(''); const [body, setBody] = useState(''); const version = useRef(0); const mergeButton = useRef<HTMLButtonElement>(null);
  const load = useCallback(async () => { const run = ++version.current; try { const [state, bin] = await Promise.all([request<InspirationState>('/inspiration'), request<{ items: TrashRecord<Bubble>[] }>('/inspiration/trash')]); if (run !== version.current) return; setItems(state.items); setTrash(bin.items); setError(''); } catch (err) { if (run === version.current) setError((err as Error).message); } finally { if (run === version.current) setLoading(false); } }, [language]);
  useEffect(() => { void load(); return () => { version.current++; }; }, [load, refreshKey]);
  const key = visibleIds.join(','); useEffect(() => { setSelected([]); setMerge(false); }, [key, mode]);
  const visible = items.filter(item => visibleIds.includes(item.id)).sort((a, b) => Number(b.pinned) - Number(a.pinned) || b.updatedAt.localeCompare(a.updatedAt));
  const removed = trash.filter(entry => `${entry.item.title} ${entry.item.body} ${entry.item.tags.join(' ')}`.toLocaleLowerCase().includes(search.toLocaleLowerCase()));
  async function fuse(event: FormEvent) { event.preventDefault(); if (busy || selected.length < 2) return; setBusy(true); setError(''); try { const saved = await request<Bubble>('/inspiration/merge', 'POST', { ids: selected, title, body }); await onChanged(); navigate(`/ideas/${encodeURIComponent(saved.id)}`); } catch (err) { setError((err as Error).message); } finally { setBusy(false); } }
  async function restore(id: string) { if (busy) return; setBusy(true); setError(''); try { await request('/inspiration/restore', 'POST', { ids: [id] }); await load(); await onChanged(); setMessage(t('想法与完整时间线已恢复。', 'Idea and its full timeline restored.')); } catch (err) { setError((err as Error).message); } finally { setBusy(false); } }
  return <section className="idea-board" aria-label={mode === 'garden' ? t('灵感气泡园', 'Idea bubble garden') : t('想法回收站', 'Idea recycle bin')}>
    {error && <Notice error>{error} <button className="pw-text-button" disabled={busy} onClick={() => void load()}>{t('重试', 'Retry')}</button></Notice>}{message && <Notice>{message}</Notice>}
    {mode === 'garden' && <div className="idea-selection"><p>{selected.length ? t(`选中了 ${selected.length} 颗气泡`, `${selected.length} bubbles selected`) : t('勾选两颗或更多气泡，试着把它们融合。', 'Select two or more bubbles to combine them.')}</p><div className="idea-actions"><button ref={mergeButton} className="pw-button" disabled={busy || selected.length < 2} onClick={() => setMerge(true)}>{t('融合所选', 'Fuse selected')}</button>{selected.length > 0 && <button className="pw-text-button" disabled={busy} onClick={() => { setSelected([]); setMerge(false); }}>{t('清空选择', 'Clear selection')}</button>}</div></div>}
    {merge && mode === 'garden' && <form className="idea-merge" onSubmit={fuse}><h2>{t('这几个想法怎样发生联系？', 'How do these ideas connect?')}</h2><p>{selected.map(id => items.find(item => item.id === id)?.title).join(' + ')}</p><fieldset className="idea-fields" disabled={busy}><label>{t('给新组合起个名字', 'Name the new combination')}<input autoFocus value={title} onChange={e => setTitle(e.target.value)} required maxLength={120} placeholder={t('例如：一封会开花的信', 'For example: a letter that blooms')}/></label><label>{t('它们之间的联系', 'The connection between them')}<textarea value={body} onChange={e => setBody(e.target.value)} rows={3} maxLength={8000}/></label></fieldset><p className="idea-help">{t('创建新气泡后，在“接着想下去”中与 Qwen 探索它们的可能性。所有原始想法和时间线保留。', 'Open the new bubble to explore its possibilities with Qwen. Every original idea and timeline is kept.')}</p><div className="idea-actions"><button className="pw-button primary" disabled={busy || !title.trim()}>{busy ? t('融合中…', 'Combining…') : t('融合并打开一起想', 'Combine & think together')}</button><button className="pw-button" type="button" disabled={busy} onClick={() => { setMerge(false); mergeButton.current?.focus(); }}>{t('取消', 'Cancel')}</button></div></form>}
    {loading ? <p className="pw-loading" role="status">{t('正在打开气泡园…', 'Opening your bubble garden…')}</p> : mode === 'trash' ? <><p className="idea-help">{t('移除后 30 天内可恢复，包含完整时间线、原状态和来源关系。', 'Restore within 30 days, including the complete timeline, original status and source links.')}</p>{removed.length ? <ul className="idea-trash">{removed.map(entry => <li key={entry.item.id}><div><strong>{entry.item.title}</strong><small>{t('可恢复至 ', 'Restore until ')}{dateLabel(entry.expiresAt, locale)}</small></div><button className="pw-button" disabled={busy || Date.parse(entry.expiresAt) <= Date.now()} onClick={() => void restore(entry.item.id)}>{Date.parse(entry.expiresAt) <= Date.now() ? t('已过期', 'Expired') : t('恢复', 'Restore')}</button></li>)}</ul> : <Empty title={t('回收站是空的', 'The recycle bin is empty')}><p>{t('移除的想法会在这里保留 30 天。', 'Removed ideas stay here for 30 days.')}</p></Empty>}</> : visible.length ? <div className="idea-bubbles is-garden" role="list">{visible.map(item => <article role="listitem" className={`idea-bubble${selected.includes(item.id) ? ' is-selected' : ''}${item.pinned ? ' is-pinned' : ''}`} key={item.id}><label className="idea-select"><input type="checkbox" aria-label={`${t('选择气泡', 'Select bubble')}: ${item.title}`} checked={selected.includes(item.id)} disabled={busy || (!selected.includes(item.id) && selected.length >= 8)} onChange={e => setSelected(previous => e.target.checked ? [...previous, item.id] : previous.filter(id => id !== item.id))}/><span>{t('选择', 'Select')}</span></label><Link className="idea-bubble-open" to={`/ideas/${encodeURIComponent(item.id)}`}><strong>{item.title}</strong>{item.body && <span className="idea-bubble-body">{item.body}</span>}<span className="idea-bubble-meta">{item.pinned && <span>{t('置顶', 'Pinned')}</span>}{item.sources.length > 0 && <span>{t(`${item.sources.length} 个来源`, `${item.sources.length} sources`)}</span>}{item.projectId && <span>{t('已立项', 'Project linked')}</span>}</span>{item.tags.length > 0 && <span className="idea-tags">{item.tags.slice(0, 3).map(tag => <span key={tag}>{tag}</span>)}</span>}</Link></article>)}</div> : <Empty title={t('给忽然想到的事，留个位置', 'Make room for a passing thought')}><p>{t('新建一个想法，然后从气泡园里打开、补充或融合。', 'Create an idea, then open, develop or combine it from the bubble garden.')}</p></Empty>}
  </section>;
}
