import { useEffect, useRef, useState } from 'react';
import { request, dateLabel } from './api';
import { usePreferences } from './Preferences';
import { Notice } from './shared';
import { syncScopes, type SyncScope, type SyncStatus, type SyncPreview, type SyncDevice, type SyncConflict } from './private-sync-model';
import '../styles/private-sync.css';

function canKeepCloudReading(conflict: SyncConflict): boolean {
  if (conflict.reason !== 'same_source' || !conflict.remote || typeof conflict.remote !== 'object' || !conflict.local || typeof conflict.local !== 'object') return false;
  const remote = conflict.remote as Record<string, unknown>; const local = conflict.local as Record<string, unknown>;
  return remote.kind === 'reading' && !!remote.body && typeof remote.body === 'object' && !Array.isArray(remote.body) && !remote.deletedAt
    && local.kind === 'reading' && !!local.body && typeof local.body === 'object' && !Array.isArray(local.body)
    && (!local.deletedAt || (typeof local.expiresAt === 'string' && Date.parse(local.expiresAt) > Date.now()));
}

export default function PrivateSync() {
  const { t, language, locale } = usePreferences();
  const [status, setStatus] = useState<SyncStatus | null>(null); const [devices, setDevices] = useState<SyncDevice[]>([]);
  const [canManageDevices, setCanManageDevices] = useState(false);
  const [scopes, setScopes] = useState<SyncScope[]>([]); const [preview, setPreview] = useState<SyncPreview | null>(null);
  const [busy, setBusy] = useState(''); const [error, setError] = useState(''); const [feedback, setFeedback] = useState('');
  const [approve, setApprove] = useState(false); const [revoke, setRevoke] = useState<SyncDevice | null>(null);
  const [resolution, setResolution] = useState<{ conflict: SyncConflict; choice: 'local' | 'remote' | 'merged'; body: string } | null>(null);
  const alive = useRef(true); const confirmation = useRef<HTMLDivElement>(null);
  async function load() {
    const [next, list] = await Promise.allSettled([request<SyncStatus>('/private-sync/status'), request<{ items: SyncDevice[]; canManage?: boolean }>('/private-sync/devices')]);
    if (!alive.current) return;
    if (next.status === 'fulfilled') {
      setStatus(next.value);
      if (next.value.mode === 'revoked') { setApprove(false); setRevoke(null); setResolution(null); }
    }
    if (next.status === 'fulfilled' && next.value.mode !== 'revoked' && list.status === 'fulfilled') {
      setDevices(list.value.items); setCanManageDevices(list.value.canManage ?? !!list.value.items.find(device => device.id === next.value.device.id)?.administrator);
    } else { setDevices([]); setCanManageDevices(false); }
    // Device-list permissions can fail independently of the local status API.
    // Commit a successful status read before surfacing either failure.
    if (next.status === 'rejected') throw next.reason;
    if (list.status === 'rejected') throw list.reason;
  }
  useEffect(() => { alive.current = true; void load().catch(err => { if (alive.current) setError((err as Error).message); }); return () => { alive.current = false; }; }, [language]);
  useEffect(() => { if (approve || revoke || resolution) confirmation.current?.focus(); }, [approve, revoke, resolution]);
  const label = (scope: string) => ({ todos: t('待办', 'Tasks'), reading: t('书架与笔记', 'Shelf & notes'), ideas: t('灵感与时间线', 'Ideas & timelines'), learning: t('学习计划', 'Study plans'), journal: t('工作日记', 'Work journal'), projects: t('项目关联与进展', 'Project context') }[scope] ?? scope);
  const mode = status ? ({ local_only: t('仅保存在本机', 'Local storage only'), preview_required: t('等待确认同步范围', 'Awaiting scope approval'), offline: t('云端不可用 · 本机仍可使用', 'Cloud unavailable · local data stays usable'), pending: t('有修改等待同步', 'Changes awaiting sync'), synced: t('已完成上次同步', 'Last sync completed'), conflict: t('有冲突等待处理', 'Conflicts need your decision'), revoked: t('此设备访问已撤销', 'This device access is revoked') }[status.mode]) : t('正在读取同步状态…', 'Reading sync status…');
  async function action(name: string, work: () => Promise<void>) { if (busy) return; setBusy(name); setError(''); setFeedback(''); try { await work(); } catch (err) { if (alive.current) setError((err as Error).message); } finally { if (alive.current) setBusy(''); } }
  function download() { if (!preview) return; const url = URL.createObjectURL(new Blob([JSON.stringify(preview, null, 2)], { type: 'application/json' })); const link = document.createElement('a'); link.href = url; link.download = `dailyhouse-sync-preview-${preview.id}.json`; link.click(); window.setTimeout(() => URL.revokeObjectURL(url), 1000); }
  const remoteReady = !!status?.configured && status.mode !== 'revoked';
  return <section className="pw-setting-section private-sync" aria-labelledby="private-sync-title"><div><h2 id="private-sync-title">{t('私人云端同步', 'Private cloud sync')}</h2><p>{t('你的设备共享小院记录，本机存储始终保留。', 'Share DailyHouse records across your devices while keeping local storage.')}</p></div><div className="private-sync-content">
    <p className="private-sync-state" role="status"><strong>{mode}</strong>{status && <span>{status.device.name} · {t('待同步', 'Pending')} {status.pending}</span>}</p>
    {status?.paused && <p role="status">{t('同步已暂停，修改仍保存在本机。', 'Sync is paused. Changes remain local.')}</p>}{status?.lastSyncedAt && <p className="pw-footnote">{t('上次同步：', 'Last sync: ')}{dateLabel(status.lastSyncedAt, locale)}</p>}
    {!status?.configured && <p>{t('云服务尚未配置。现在可以检查本机同步白名单，预览不会上传数据。云服务和身份验证确定后，才开放确认与同步。', 'No cloud service is configured. You can inspect the local whitelist; previews upload nothing. Approval and sync become available after the service and authentication are configured.')}</p>}
    {status?.message && <p>{status.message}</p>}
    <fieldset className="private-sync-scopes" disabled={!!busy}><legend>{t('本次预览范围（默认不选）', 'Preview scope (nothing selected by default)')}</legend>{syncScopes.map(scope => <label key={scope}><input type="checkbox" checked={scopes.includes(scope)} onChange={event => { setScopes(previous => event.target.checked ? [...previous, scope] : previous.filter(value => value !== scope)); setPreview(null); setApprove(false); }}/>{label(scope)}</label>)}</fieldset>
    <p className="pw-footnote">{t('附件副本、个人资料、账号与凭证、设备路径、外部工具完整对话不在第一阶段上传范围。预览文件可能含私人内容，请保存在自己的设备上。', 'Attachment copies, personal profile, accounts, credentials, device paths and full external conversations are excluded from phase one. A downloaded preview may contain private content; keep it on your own device.')}</p>
    <div className="idea-actions"><button className="pw-button" disabled={!!busy || !scopes.length} onClick={() => void action('preview', async () => { const next = await request<SyncPreview>('/private-sync/preview', 'POST', { scopes }); if (alive.current) { setPreview(next); setApprove(false); } })}>{busy === 'preview' ? t('检查中…', 'Inspecting…') : t('检查迁移预览', 'Inspect migration preview')}</button><button className="pw-text-button" disabled={!!busy} onClick={() => void action('refresh', load)}>{t('重新检查状态', 'Refresh status')}</button>{remoteReady && <><button className="pw-button" disabled={!!busy || !!status?.paused || status?.mode === 'preview_required'} onClick={() => void action('run', async () => { await request('/private-sync/run', 'POST', {}); await load(); })}>{t('同步已确认的范围', 'Sync approved scope')}</button>{status?.paused ? <button className="pw-button" disabled={!!busy} onClick={() => void action('resume', async () => { await request('/private-sync/resume', 'POST', {}); await load(); setFeedback(t('已恢复已确认范围的同步。', 'Sync of the approved scope resumed.')); })}>{t('恢复同步', 'Resume sync')}</button> : <button className="pw-text-button" disabled={!!busy} onClick={() => void action('pause', async () => { await request('/private-sync/pause', 'POST', {}); await load(); setFeedback(t('同步已暂停，本机记录保留。', 'Sync paused. Local records are kept.')); })}>{t('暂停同步', 'Pause sync')}</button>}</>}</div>
    {preview && <section className="private-sync-preview" aria-labelledby="sync-preview-title"><h3 id="sync-preview-title">{t('迁移预览', 'Migration preview')}</h3><p>{t('初始数据来自：', 'Initial data source: ')}<strong>{preview.device.name}</strong> · {dateLabel(preview.createdAt, locale)}</p><p>{t(`本机 ${preview.recordCount} 条记录 · 同步预览 ${preview.records.length} 项 · 将上传 ${preview.uploadCount} · 将下载 ${preview.downloadCount} · 冲突 ${preview.conflictCount}`, `${preview.recordCount} local records · ${preview.records.length} sync preview items · ${preview.uploadCount} uploads · ${preview.downloadCount} downloads · ${preview.conflictCount} conflicts`)}</p>{preview.emptyDevice && <Notice>{t('这台设备的选定范围为空。空数据不会清空云端；连接后先下载已有记录。', 'The selected scope is empty on this device. Empty data will not clear the cloud; existing records are downloaded first.')}</Notice>}<p>{t('迁移前会保留本机备份；两台设备同改一条记录时保留冲突，待你决定。暂停同步不会删除本机或云端记录。', 'A local backup precedes migration. Edits to the same record on two devices remain as a conflict for your decision. Pausing sync removes no local or cloud records.')}</p>
      <details><summary>{t(`逐项检查 ${preview.records.length} 条记录`, `Inspect ${preview.records.length} records`)}</summary><ul className="private-sync-records">{preview.records.map(record => <li key={`${record.kind}:${record.id}`}><span>{label(record.kind)} · <strong>{record.title || record.id}</strong></span><span>{({ upload: t('上传', 'Upload'), download: t('下载', 'Download'), conflict: t('保留冲突', 'Conflict'), unchanged: t('无需修改', 'Unchanged') })[record.action]}</span></li>)}</ul></details>
      <details><summary>{t('查看排除项与附件', 'Inspect exclusions & attachments')}</summary><ul>{preview.excluded.map((item, index) => <li key={index}>{item}</li>)}</ul>{preview.attachmentsExcluded.length ? <ul>{preview.attachmentsExcluded.map((file, index) => <li key={index}>{file.name} · {file.size} {t('字节（不上传）', 'bytes (excluded)')}</li>)}</ul> : <p>{t('没有附件字节上传。', 'No attachment bytes are uploaded.')}</p>}</details>
      {preview.conflictCount > 0 && <Notice>{t('确认范围不会覆盖这些冲突。执行同步后，无冲突记录可以继续；冲突记录保留双方内容，等待你逐项决定。', 'Approving the scope does not overwrite these conflicts. When sync runs, other records can proceed; conflicting records keep both versions until you review each one.')}</Notice>}
      <div className="idea-actions"><button className="pw-button" onClick={download}>{t('下载完整预览', 'Download full preview')}</button><button className="pw-button primary" disabled={!!busy || !remoteReady} onClick={() => setApprove(true)}>{t('审阅后确认此范围', 'Approve this reviewed scope')}</button><button className="pw-text-button" disabled={!!busy} onClick={() => { setPreview(null); setApprove(false); }}>{t('放弃预览', 'Discard preview')}</button></div>
      {approve && <div className="idea-delete-confirm" ref={confirmation} tabIndex={-1}><p>{t(`确认从“${preview.device.name}”同步上述范围？只批准本次预览，不上传附件和外部工具记录。`, `Approve this scope from “${preview.device.name}”? Only this preview is approved; attachments and external tool records are excluded.`)}</p><div className="idea-actions"><button className="pw-button primary" disabled={!!busy} onClick={() => void action('approve', async () => { await request('/private-sync/approve', 'POST', { previewId: preview.id, confirmed: true }); setApprove(false); await load(); setFeedback(t('同步范围已确认。', 'Sync scope approved.')); })}>{t('确认同步此预览', 'Confirm this sync preview')}</button><button className="pw-text-button" disabled={!!busy} onClick={() => setApprove(false)}>{t('取消', 'Cancel')}</button></div></div>}
    </section>}
    {!!status?.conflicts.length && <section className="private-sync-conflicts"><h3>{t('处理冲突', 'Resolve conflicts')}</h3><p>{t('两份编辑都保留。选择一份或手动合并后才会继续同步。', 'Both edits are kept. Choose one or merge them before sync continues.')}</p>{status.conflicts.map(conflict => <details key={conflict.id}><summary>{conflict.title || conflict.key}</summary>
      {conflict.reason === 'local_missing' && <p>{t('本机缺失不等同删除。可能是本机数据文件丢失或被重置；云端记录已保留。可以找回云端版本，或在再次确认后永久删除这条共享记录。', 'Missing locally does not mean deleted. The local data file may be lost or reset; the cloud record is kept. Restore the cloud version, or explicitly confirm permanent deletion of this shared record.')}</p>}
      <div className="private-sync-conflict-pair"><div><strong>{t('本机编辑', 'Local edit')}</strong><pre>{JSON.stringify(conflict.local, null, 2)}</pre></div><div><strong>{t('云端编辑', 'Cloud edit')}</strong><pre>{JSON.stringify(conflict.remote, null, 2)}</pre></div></div>{conflict.reason === 'same_source' && <p>{t('同一资料来源在两台设备有不同标识，双方都已保留。请核对迁移预览并在原记录中整理，不能在这里直接覆盖。', 'The same source has different identities on the devices. Both records are kept. Review the migration preview and reconcile the original records; direct overwrite is unavailable here.')}</p>}<div className="idea-actions">{(conflict.reason === 'same_source' ? (canKeepCloudReading(conflict) ? ['remote'] as const : []) : ['local', 'remote', 'merged'] as const).map(choice => <button key={choice} className={`pw-button ${conflict.reason === 'local_missing' && choice === 'local' ? 'idea-danger-button' : ''}`} disabled={!!busy} onClick={() => setResolution({ conflict, choice, body: JSON.stringify(conflict.local && typeof conflict.local === 'object' && 'body' in conflict.local ? conflict.local.body : conflict.local, null, 2) })}>{choice === 'local' ? (conflict.reason === 'local_missing' ? t('永久删除共享记录…', 'Permanently delete shared record…') : t('采用本机版本', 'Use local version')) : choice === 'remote' ? (canKeepCloudReading(conflict) ? t('保留云端条目并收起本机重复项', 'Keep cloud item and archive local duplicate') : conflict.reason === 'local_missing' ? t('找回云端版本', 'Restore cloud version') : t('采用云端版本', 'Use cloud version')) : t('手动合并', 'Merge manually')}</button>)}</div></details>)}</section>}
    {resolution && <div className="idea-delete-confirm" ref={confirmation} tabIndex={-1}>
      <h3>{t('确认冲突处理', 'Confirm conflict resolution')}</h3><p>{resolution.conflict.title || resolution.conflict.key} · {resolution.choice === 'local' ? t('采用本机版本', 'Use local version') : resolution.choice === 'remote' ? t('采用云端版本', 'Use cloud version') : t('保存合并后的记录', 'Save merged record')}</p>
      {canKeepCloudReading(resolution.conflict) && <p>{t('云端条目的标识将成为统一记录。本机重复条目及其最新笔记会保留在 30 天回收站；已在回收站的条目保持原恢复期限。不会自动合并两份笔记。这次明确确认会解除该来源的移除抑制，普通删除仍保留抑制。', 'The cloud item becomes the shared record identity. The local duplicate and its latest notes stay in the 30-day recycle bin; an already archived item keeps its original deadline. Notes are not merged automatically. This explicit confirmation clears the source’s removal suppression; ordinary deletion keeps suppression.')}</p>}
      {resolution.conflict.reason === 'local_missing' && resolution.choice === 'local' && <p>{t('确认将本机缺失视为永久删除？这将删除云端的这条小院记录，并传播到其他设备，不能从小院回收站恢复。外部对话、项目目录、GitHub 仓库和原始资料不受影响。', 'Treat this missing local record as a permanent deletion? This deletes the DailyHouse record in the cloud and on other devices, with no recovery from the DailyHouse recycle bin. External conversations, project directories, GitHub repositories and original files are unaffected.')}</p>}
      {resolution.choice === 'merged' && <label>{t('合并后的 JSON 记录', 'Merged JSON record')}<textarea rows={12} value={resolution.body} onChange={event => setResolution({ ...resolution, body: event.target.value })}/></label>}<div className="idea-actions"><button className={`pw-button ${resolution.conflict.reason === 'local_missing' && resolution.choice === 'local' ? 'idea-danger-button' : 'primary'}`} disabled={!!busy} onClick={() => void action('resolve', async () => { const body = resolution.choice === 'merged' ? JSON.parse(resolution.body) : undefined; await request(`/private-sync/conflicts/${encodeURIComponent(resolution.conflict.id)}/resolve`, 'POST', { choice: resolution.choice, ...(body === undefined ? {} : { body }), confirmed: true }); setResolution(null); await load(); })}>{resolution.conflict.reason === 'local_missing' && resolution.choice === 'local' ? t('确认从所有设备永久删除', 'Permanently delete on all devices') : canKeepCloudReading(resolution.conflict) ? t('确认保留云端条目并收起本机重复项', 'Confirm cloud item and archive local duplicate') : t('确认处理', 'Confirm resolution')}</button><button className="pw-text-button" disabled={!!busy} onClick={() => setResolution(null)}>{t('取消', 'Cancel')}</button></div>
    </div>}
    {!!devices.length && <details className="private-sync-devices"><summary>{t('授权设备', 'Authorized devices')} ({devices.length})</summary><ul>{devices.map(device => <li key={device.id}><div><strong>{device.name}</strong><small>{device.id === status?.device.id ? t('当前设备', 'This device') : t('其他设备', 'Another device')} · {(device.revoked || device.revokedAt) ? t('已撤销', 'Revoked') : t('已授权', 'Authorized')}</small></div>{canManageDevices && !(device.revoked || device.revokedAt) && <button className="pw-text-button idea-danger" disabled={!!busy || !remoteReady} onClick={() => setRevoke(device)}>{t('撤销访问', 'Revoke access')}</button>}</li>)}</ul></details>}
    {revoke && <div className="idea-delete-confirm" ref={confirmation} tabIndex={-1}><p>{t(`撤销“${revoke.name}”的云端访问？它将不能读取或写入云端，本机已有记录仍保留。`, `Revoke cloud access for “${revoke.name}”? It will no longer read or write cloud data. Its existing local records remain.`)}</p><div className="idea-actions"><button className="pw-button idea-danger-button" disabled={!!busy} onClick={() => void action('revoke', async () => { await request(`/private-sync/devices/${encodeURIComponent(revoke.id)}/revoke`, 'POST', { confirmed: true }); setRevoke(null); await load(); })}>{t('确认撤销此设备', 'Revoke this device')}</button><button className="pw-text-button" disabled={!!busy} onClick={() => setRevoke(null)}>{t('取消', 'Cancel')}</button></div></div>}
    <div aria-live="polite">{error && <Notice error>{error}</Notice>}{feedback && <Notice>{feedback}</Notice>}</div>
  </div></section>;
}
