import { useEffect, useRef, useState } from 'react';
import { ArrowRight, GitCommit } from 'pixelarticons/react';
import { request } from './api';
import { usePreferences } from './Preferences';
import { Notice } from './shared';
import '../styles/project-history.css';

type Commit = { hash: string; shortHash: string; subject: string; message: string; author: { name: string; email: string }; authoredAt: string; committedAt: string; parents: string[]; refs: string[]; url?: string };
type HistoryPage = { status: 'ready' | 'empty' | 'not_repository' | 'missing' | 'error'; source?: 'local_git' | 'remote_tracking'; range?: 'locally_available_refs' | 'selected_ref'; message?: string; items: Commit[]; refs: { name: string; label: string; kind: 'branch' | 'remote' | 'tag'; hash: string; source?: 'local_git' | 'remote_tracking' }[]; selectedRef: string; shallow: boolean; snapshotAt: string | null; nextCursor: string | null; total?: number };
type GithubHistory = { source: 'github_api'; fetchedAt: string; repoUrl: string; items: Commit[]; nextPage: number | null; complete: false; page: number; limit: number };
export default function ProjectCommitHistory({ projectId, projectTitle, githubAvailable = false }: { projectId: string; projectTitle: string; githubAvailable?: boolean }) {
  const { t, language, locale } = usePreferences(); const [open, setOpen] = useState(false); const [page, setPage] = useState<HistoryPage | null>(null); const [selection, setSelection] = useState('all'); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const generation = useRef(0); const pending = useRef(false); const more = useRef<HTMLButtonElement>(null);
  useEffect(() => () => { generation.current++; }, [projectId]);
  const [github, setGithub] = useState<GithubHistory | null>(null); const [githubBusy, setGithubBusy] = useState(false); const [githubError, setGithubError] = useState(''); const githubGeneration = useRef(0); const githubPending = useRef(false);
  useEffect(() => () => { githubGeneration.current++; }, [projectId]);
  async function queryGithub(append = false) { if (githubPending.current || !githubAvailable) return; githubPending.current = true; const current = ++githubGeneration.current; setGithubBusy(true); setGithubError(''); try { const next = await request<GithubHistory>(`/project-resume/${encodeURIComponent(projectId)}/github-history`, 'POST', { page: append && github?.nextPage ? github.nextPage : 1, limit: 30 }); if (current !== githubGeneration.current) return; setGithub(previous => append && previous ? { ...next, items: [...previous.items, ...next.items.filter(item => !previous.items.some(old => old.hash === item.hash))] } : next); } catch (err) { if (current === githubGeneration.current) setGithubError((err as Error).message); } finally { if (current === githubGeneration.current) { githubPending.current = false; setGithubBusy(false); } } }
  async function load(ref = selection, append = false) {
    if (pending.current) return; pending.current = true; setLoading(true); setError(''); const run = ++generation.current;
    const query = new URLSearchParams({ limit: '30', ...(append && page?.nextCursor ? { cursor: page.nextCursor } : { ref }) });
    try {
      const next = await request<HistoryPage>(`/project-resume/${encodeURIComponent(projectId)}/history?${query}`);
      if (run !== generation.current) return;
      if (next.status === 'error') { setError(next.message || t('暂时无法读取提交历史，请重试。', 'Commit history could not be read. Please retry.')); return; }
      setPage(previous => append && previous ? { ...next, items: [...previous.items, ...next.items.filter(item => !previous.items.some(old => old.hash === item.hash))] } : next);
      setSelection(next.selectedRef || ref);
    } catch (err) { if (run === generation.current) setError((err as Error).message); }
    finally { if (run === generation.current) { pending.current = false; setLoading(false); } }
  }
  const fullDate = (date: string) => { const value = new Date(date); return Number.isNaN(value.getTime()) ? date : value.toLocaleString(locale, { year: 'numeric', month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' }); };
  const statusMessage = page?.status === 'empty' ? t('这个仓库还没有提交。第一次提交后再刷新。', 'This repository has no commits yet. Refresh after its first commit.') : page?.status === 'missing' ? t('本机工作目录暂时不可用，恢复目录后重新读取。', 'The workspace is unavailable. Restore its location, then refresh.') : page?.status === 'not_repository' ? t('这个工作目录还不是 Git 仓库。', 'This workspace is not a Git repository yet.') : '';
  return <section className="project-history"><button className="pw-text-button project-history-toggle" aria-expanded={open} aria-controls={`history-${projectId}`} onClick={() => { const next = !open; setOpen(next); if (next && !page && !loading) void load(); }}><GitCommit width={19}/>{t('查看本机提交历史', 'View local commit history')}<span aria-hidden="true">{open ? '−' : '+'}</span></button>
    {open && <div id={`history-${projectId}`} className="project-history-panel" aria-label={t(`${projectTitle} 的提交历史`, `Commit history for ${projectTitle}`)}>
      <div className="project-history-controls"><label><span>{t('历史范围', 'History scope')}</span><select aria-label={t('选择提交历史范围', 'Choose commit history scope')} value={selection} disabled={loading} onChange={event => { const value = event.target.value; void load(value); }}><option value="all">{t('本机可用引用（含缓存远程）', 'Locally available refs (including cached remotes)')}</option><option value="HEAD">{t('当前 HEAD', 'Current HEAD')}</option>{page?.refs.map(ref => <option key={ref.name} value={ref.name}>{ref.kind === 'tag' ? t('标签', 'Tag') : ref.kind === 'remote' ? t('本机远程跟踪缓存', 'Local remote-tracking cache') : t('分支', 'Branch')} · {ref.label}</option>)}</select></label><button className="pw-text-button" disabled={loading} onClick={() => void load(selection)}>{t('刷新历史', 'Refresh history')}</button></div>
      <p className="project-history-scope">{page?.source === 'remote_tracking' ? t('来源：本机远程跟踪缓存，未查询 GitHub。', 'Source: local remote-tracking cache; GitHub has not been queried.') : t('来源：本机 Git（包括本机可用的缓存远程引用）。', 'Source: local Git, including cached remote refs available on this device.')} {page?.shallow ? t('这是浅克隆，仅展示本机已下载的历史。', 'This is a shallow clone. Only history downloaded on this device is available.') : t('只读取本机已保存的历史，不执行 fetch。远程跟踪引用的最近 fetch 时间未知。', 'Only locally saved history is read; no fetch is performed. The last fetch time of remote-tracking refs is unknown.')}{page?.snapshotAt && <> {t('快照时间：', 'Snapshot: ')}<time dateTime={page.snapshotAt}>{fullDate(page.snapshotAt)}</time></>}</p>
      {error && <Notice error>{error} <button className="pw-text-button" disabled={loading} onClick={() => void load(selection)}>{t('重新读取历史', 'Reload history')}</button></Notice>}
      {statusMessage && <p className="project-history-empty">{statusMessage}</p>}
      {page?.items.length ? <><p className="project-history-count">{typeof page.total === 'number' ? t(`已显示 ${page.items.length} / ${page.total} 条提交`, `Showing ${page.items.length} of ${page.total} commits`) : t(`已显示 ${page.items.length} 条提交`, `Showing ${page.items.length} commits`)}</p><ol className="project-commits">{page.items.map(commit => <li key={commit.hash}><details><summary><span className="project-commit-subject">{commit.subject || t('无提交标题', 'Untitled commit')}</span><span className="project-commit-meta"><code>{commit.shortHash}</code><span>{commit.author.name}</span><time dateTime={commit.committedAt}>{fullDate(commit.committedAt)}</time></span></summary>{commit.refs.length > 0 && <div className="project-commit-refs">{commit.refs.map(ref => <span key={ref}>{ref}</span>)}</div>}<pre className="project-commit-message">{commit.message}</pre><dl className="project-commit-facts"><dt>{t('完整哈希', 'Full hash')}</dt><dd><code>{commit.hash}</code></dd><dt>{t('作者', 'Author')}</dt><dd>{commit.author.name}{commit.author.email && <> &lt;{commit.author.email}&gt;</>}</dd><dt>{t('创作时间', 'Authored')}</dt><dd><time dateTime={commit.authoredAt}>{fullDate(commit.authoredAt)}</time></dd><dt>{t('提交时间', 'Committed')}</dt><dd><time dateTime={commit.committedAt}>{fullDate(commit.committedAt)}</time></dd>{commit.parents.length > 0 && <><dt>{t('父提交', 'Parents')}</dt><dd>{commit.parents.map(parent => <code key={parent}>{parent}</code>)}</dd></>}</dl>{commit.url && <a className="pw-text-button" href={commit.url} target="_blank" rel="noreferrer">{t('在 GitHub 查看此提交', 'View this commit on GitHub')}<ArrowRight width={15}/></a>}</details></li>)}</ol></> : null}
      {loading && <p className="project-history-loading" role="status">{t('正在读取提交历史…', 'Reading commit history…')}</p>}
      {page?.nextCursor && <button ref={more} className="pw-button small" disabled={loading} onClick={() => void load(selection, true)}>{loading ? t('读取中…', 'Loading…') : t('加载更多提交', 'Load more commits')}</button>}{page?.status === 'ready' && !page.nextCursor && !!page.items.length && <p className="project-history-end">{language === 'en' ? 'All downloaded records in this selected local range are shown.' : '此本机范围内已下载的记录已展示完。'}</p>}
      <div className="project-github-history"><h3>{t('单独查询 GitHub 已推送记录', 'Query pushed GitHub history separately')}</h3><p className="project-history-scope">{t('只有你点击查询时才读取 GitHub API，不 fetch、不切换分支、不修改仓库。其他设备未推送的提交、未提交修改和本机分支不会出现。', 'GitHub API is read only when you click query. No fetch, branch switch or repository change occurs. Unpushed commits, uncommitted edits and local branches on other devices will not appear.')}</p><button className="pw-button" disabled={githubBusy || !githubAvailable} onClick={() => void queryGithub()}>{githubBusy ? t('查询中…', 'Querying…') : t('查询 GitHub 提交', 'Query GitHub commits')}</button>{!githubAvailable && <p className="project-history-scope">{t('需要已验证的当前 Git 远程仓库关联；同名推测关联不能用来查询。', 'A verified current Git remote association is required. An inferred matching name cannot be queried.')}</p>}{githubError && <Notice error>{githubError}</Notice>}
        {github && <><p className="project-history-scope">{t('来源：GitHub API · 实际查询时间：', 'Source: GitHub API · queried at: ')}<time dateTime={github.fetchedAt}>{fullDate(github.fetchedAt)}</time> · {t('这是分页查询结果，不称为完整历史。', 'These are paginated results, not a claim of complete history.')}</p><p className="project-history-count">{t(`本次已显示 ${github.items.length} 条已推送提交`, `${github.items.length} pushed commits shown in this query`)}</p><ol className="project-commits">{github.items.map(commit => <li key={commit.hash}><details><summary><span className="project-commit-subject">{commit.subject}</span><span className="project-commit-meta"><code>{commit.shortHash}</code><span>{commit.author.name}</span><time dateTime={commit.committedAt}>{fullDate(commit.committedAt)}</time></span></summary><pre className="project-commit-message">{commit.message}</pre>{commit.url && <a className="pw-text-button" href={commit.url} target="_blank" rel="noopener noreferrer">{t('在 GitHub 查看提交', 'View commit on GitHub')}</a>}</details></li>)}</ol>{!github.items.length && <p>{t('此页没有返回提交。', 'No commits were returned on this page.')}</p>}{github.nextPage && <button className="pw-button" disabled={githubBusy} onClick={() => void queryGithub(true)}>{t('查询下一页 GitHub 提交', 'Query next page of GitHub commits')}</button>}</>}
      </div>
    </div>}
  </section>;
}
