import { useCallback, useEffect, useRef, useState, type FormEvent } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { Close, Search } from 'pixelarticons/react';
import { request, dateLabel } from './api';
import { usePreferences } from './Preferences';
import { useWorkspace } from './Workspace';
import { Empty, Notice, PageHead } from './shared';
import type { Project, TrashRecord } from './inspiration-model';
import ProjectFields, { type ProjectPlan } from './ProjectFields';
import '../styles/inspiration.css';

function ProjectEditor({ project, onChanged, onClose }: { project: Project; onChanged: () => Promise<void>; onClose: () => void }) {
  const { t, locale } = usePreferences(); const { refresh } = useWorkspace(); const [plan, setPlan] = useState<ProjectPlan>({ title: project.title, goal: project.goal, mvp: project.mvp, acceptance: project.acceptance, nextStep: project.nextStep }); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [remove, setRemove] = useState(false); const [todoId, setTodoId] = useState(project.todoId); const heading = useRef<HTMLHeadingElement>(null);
  useEffect(() => { heading.current?.focus({ preventScroll: true }); }, []);
  const dirty = plan.title !== project.title || plan.goal !== project.goal || plan.nextStep !== project.nextStep || plan.mvp.join('\n') !== project.mvp.join('\n') || plan.acceptance.join('\n') !== project.acceptance.join('\n');
  async function action(work: () => Promise<unknown>, success: string) { if (busy) return; setBusy(true); setError(''); setMessage(''); try { await work(); await onChanged(); setMessage(success); } catch (err) { setError((err as Error).message); } finally { setBusy(false); } }
  async function save(event: FormEvent) { event.preventDefault(); await action(async () => { const saved = await request<Project>(`/projects/${project.id}`, 'PATCH', { ...plan, revision: project.revision }); setPlan({ title: saved.title, goal: saved.goal, mvp: saved.mvp, acceptance: saved.acceptance, nextStep: saved.nextStep }); if (saved.nextStepId !== project.nextStepId) setTodoId(saved.todoId); }, t('项目记录已更新。', 'Project record updated.')); }
  async function addTodo() { if (busy || dirty) return; setBusy(true); setError(''); setMessage(''); try { const result = await request<{ todoId: string; created: boolean; deleted: boolean }>(`/projects/${project.id}/todo`, 'POST'); await onChanged(); await refresh(); setTodoId(result.deleted ? undefined : result.todoId); setMessage(result.deleted ? t('这一步的待办已被删除，不会自动重建。请写下新的下一步再添加。', 'The task for this step was deleted and will not be recreated. Write a new next step to add another task.') : result.created ? t('下一步已加入今日待办。', 'Next step added to your tasks.') : t('这一步已在待办中，未重复添加。', 'This step is already in your tasks; no duplicate was added.')); } catch (err) { setError((err as Error).message); } finally { setBusy(false); } }
  return <aside className="idea-editor project-editor" aria-labelledby="project-editor-title"><div className="idea-section-title"><h2 ref={heading} tabIndex={-1} id="project-editor-title">{t('推进这个项目', 'Move this project forward')}</h2><button className="pw-icon-button" disabled={busy} aria-label={t('关闭项目详情', 'Close project details')} onClick={onClose}><Close width={20} height={20}/></button></div><p className="idea-meta">{t('更新于 ', 'Updated ')}{dateLabel(project.updatedAt, locale)}{project.finishedAt && <> · {t('完成于 ', 'Finished ')}{dateLabel(project.finishedAt, locale)}</>}</p><form onSubmit={save}><ProjectFields value={plan} onChange={setPlan} disabled={busy}/><div className="idea-actions"><button className="pw-button primary" disabled={busy || !dirty || !plan.title.trim() || !plan.goal.trim()}>{busy ? t('保存中…', 'Saving…') : t('保存项目', 'Save project')}</button>{dirty && <span className="idea-meta">{t('有未保存内容', 'Unsaved changes')}</span>}</div></form>
    {error && <Notice error>{error}</Notice>}{message && <Notice>{message}</Notice>}
    <section className="project-next-step"><h3>{t('只推进下一小步', 'Move one small step forward')}</h3><p>{project.nextStep || t('先写一个明确、可以开始的动作。', 'Write a clear action you can start with.')}</p><div className="idea-actions"><button className="pw-button primary" disabled={busy || dirty || !project.nextStep.trim() || project.status !== 'active'} onClick={() => void addTodo()}>{t('把下一步加入待办', 'Add next step to tasks')}</button>{todoId && <Link className="pw-text-button" to="/todos">{t('打开今日待办', 'Open tasks')}</Link>}</div><p className="idea-meta">{dirty ? t('先保存修改，再添加待办。', 'Save changes before adding a task.') : t('同一步骤重复点击不会重复添加；更改下一步不会修改旧待办。', 'The same step is added once. Changing the next step does not edit an existing task.')}</p></section>
    <section className="idea-sources"><h3>{t('最初的灵感', 'Where it began')}</h3><strong>{project.sourceSnapshot.title}</strong>{project.sourceSnapshot.body && <p className="idea-prewrap">{project.sourceSnapshot.body}</p>}<Link className="pw-text-button" to={`/ideas/${encodeURIComponent(project.sourceBubbleId)}`}>{t('回到来源气泡', 'Return to the source bubble')}</Link><p className="idea-meta">{t('项目和原灵感分别保存，编辑一边不会覆盖另一边。', 'Project and idea are saved separately. Editing one never overwrites the other.')}</p></section>
    <div className="idea-actions idea-record-actions"><button className="pw-button" disabled={busy || dirty} onClick={() => void action(() => request(`/projects/${project.id}`, 'PATCH', { revision: project.revision, status: project.status === 'done' ? 'active' : 'done' }), project.status === 'done' ? t('项目已重新开始。', 'Project reopened.') : t('项目已完成，可在“已完成”中回看。', 'Project completed. Find it under Finished.'))}>{project.status === 'done' ? t('重新开始', 'Reopen project') : t('标记项目完成', 'Mark project finished')}</button><button className="pw-text-button" disabled={busy || dirty} onClick={() => void action(() => request(`/projects/${project.id}`, 'PATCH', { revision: project.revision, status: project.status === 'archived' ? 'active' : 'archived' }), t('项目状态已更新。', 'Project status updated.'))}>{project.status === 'archived' ? t('恢复进行中', 'Return to active') : t('归档项目', 'Archive project')}</button><button className="pw-text-button idea-danger" disabled={busy} onClick={() => setRemove(true)}>{t('移除项目', 'Remove project')}</button></div>
    {remove && <div className="idea-confirm"><p>{t('项目记录将移入 30 天回收站。来源灵感、已有待办和本机文件都保留。', 'Move this project record to the 30-day recycle bin. The source idea, existing tasks and local files are kept.')}</p><div className="idea-actions"><button className="pw-button" disabled={busy} onClick={() => setRemove(false)}>{t('取消', 'Cancel')}</button><button className="pw-button" disabled={busy} onClick={() => void action(async () => { await request(`/projects/${project.id}`, 'DELETE'); onClose(); }, t('项目已移入回收站。', 'Project moved to the recycle bin.'))}>{t('确认移除项目', 'Remove this project')}</button></div></div>}
  </aside>;
}

export default function ProjectsPage() {
  const { t, language, locale } = usePreferences(); const [params, setParams] = useSearchParams(); const [items, setItems] = useState<Project[]>([]); const [trash, setTrash] = useState<TrashRecord<Project>[]>([]); const [status, setStatus] = useState<'active' | 'done' | 'archived' | 'trash'>('active'); const [search, setSearch] = useState(''); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [message, setMessage] = useState(''); const version = useRef(0); const firstTab = useRef<HTMLButtonElement>(null);
  const load = useCallback(async () => { const current = ++version.current; try { const [result, bin] = await Promise.all([request<{ items: Project[] }>('/projects'), request<{ items: TrashRecord<Project>[] }>('/projects/trash')]); if (current !== version.current) return; setItems(result.items); setTrash(bin.items); setError(''); } catch (err) { if (current === version.current) setError((err as Error).message); } finally { if (current === version.current) setLoading(false); } }, [language]);
  useEffect(() => { void load(); return () => { version.current++; }; }, [load]);
  const matches = (project: Project) => `${project.title} ${project.goal} ${project.nextStep}`.toLocaleLowerCase().includes(search.toLocaleLowerCase()); const visible = [...items].filter(project => project.status === status && matches(project)).sort((a, b) => b.updatedAt.localeCompare(a.updatedAt)); const selected = items.find(project => project.id === params.get('project')); const removed = trash.filter(entry => matches(entry.item));
  function close() { setParams({}); firstTab.current?.focus(); }
  async function restore(id: string) { if (busy) return; setBusy(true); setError(''); try { await request('/projects/restore', 'POST', { ids: [id] }); await load(); setMessage(t('项目已恢复，原状态和来源关系保留。', 'Project restored with its original status and source links.')); } catch (err) { setError((err as Error).message); } finally { setBusy(false); } }
  return <div className="projects-page"><PageHead title={t('项目库', 'Project library')} description={t('把想做的事缩成一个可以开始的版本，记住下一步。', 'Keep a small, achievable version in sight — and remember the next step.')}><Link className="pw-button" to="/ideas">{t('从灵感开始', 'Start with an idea')}</Link></PageHead><div className="idea-toolbar"><div className="idea-tabs" role="group" aria-label={t('项目状态', 'Project status')}>{(['active', 'done', 'archived', 'trash'] as const).map(value => <button ref={value === 'active' ? firstTab : undefined} className={`pw-button${status === value ? ' primary' : ''}`} aria-pressed={status === value} key={value} onClick={() => { setStatus(value); close(); }}>{value === 'active' ? t('进行中', 'Active') : value === 'done' ? t('已完成', 'Finished') : value === 'archived' ? t('已归档', 'Archived') : t('回收站', 'Recycle bin')}<span>{value === 'trash' ? trash.length : items.filter(project => project.status === value).length}</span></button>)}</div><button className="pw-text-button" disabled={busy} onClick={() => void load()}>{t('刷新', 'Refresh')}</button></div><div className="idea-filter"><label className="pw-search"><Search width={18} height={18}/><input aria-label={t('搜索项目', 'Search projects')} placeholder={t('搜索项目或下一步…', 'Search projects or next steps…')} value={search} onChange={e => setSearch(e.target.value)}/></label></div>{error && <Notice error>{error}</Notice>}{message && <Notice>{message}</Notice>}
    {loading ? <p role="status" className="pw-loading">{t('正在打开项目库…', 'Opening project library…')}</p> : <div className={`idea-workspace${selected && status !== 'trash' ? ' has-editor' : ''}`}><section aria-label={t('项目列表', 'Project list')}>{status === 'trash' ? <><p className="idea-help">{t('30 天内可恢复。回收站只管理项目记录，不操作本机代码或文件。', 'Restore within 30 days. This recycle bin manages project records, never local code or files.')}</p>{removed.length ? <ul className="idea-trash">{removed.map(entry => <li key={entry.item.id}><div><strong>{entry.item.title}</strong><small>{t('可恢复至 ', 'Restore until ')}{dateLabel(entry.expiresAt, locale)}</small></div><button className="pw-button" disabled={busy || Date.parse(entry.expiresAt) <= Date.now()} onClick={() => void restore(entry.item.id)}>{Date.parse(entry.expiresAt) <= Date.now() ? t('已过期', 'Expired') : t('恢复', 'Restore')}</button></li>)}</ul> : <Empty title={t('回收站是空的', 'The recycle bin is empty')}><p>{t('移除的项目记录会在这里保留 30 天。', 'Removed project records stay here for 30 days.')}</p></Empty>}</> : visible.length ? <ul className="project-list">{visible.map(project => <li key={project.id} className={project.id === selected?.id ? 'is-selected' : ''}><button onClick={() => setParams({ project: project.id })} aria-expanded={project.id === selected?.id}><strong>{project.title}</strong><p>{project.goal}</p><span className="project-next-label">{t('下一步', 'Next step')}</span><span>{project.nextStep || t('待写下第一个行动', 'Write the first action')}</span><small>{t('更新于 ', 'Updated ')}{dateLabel(project.updatedAt, locale)}</small></button></li>)}</ul> : <Empty title={search ? t('没有找到这个项目', 'No matching projects') : status === 'active' ? t('等一颗灵感准备好出发', 'When an idea is ready to begin') : t('这里还没有项目', 'No projects here yet')}><p>{search ? t('换个关键词再试试。', 'Try another search term.') : t('在灵感气泡中确认目标、最小版本和第一步，再放进项目库。', 'Review the goal, smallest version and first step in an idea bubble, then create a project.')}</p></Empty>}</section>{selected && status !== 'trash' && <ProjectEditor key={selected.id} project={selected} onChanged={load} onClose={close}/>}</div>}
    {params.get('project') && !selected && !loading && <Notice>{t('该项目可能已移入回收站，恢复后可继续编辑。', 'This project may be in the recycle bin. Restore it to continue editing.')} <button className="pw-text-button" onClick={() => { setStatus('trash'); close(); }}>{t('查看项目回收站', 'Open project recycle bin')}</button></Notice>}
  </div>;
}
