import { useCallback, useEffect, useRef, useState, type FormEvent } from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, Check, Plus } from 'pixelarticons/react';
import { dateLabel, request } from './api';
import { usePreferences } from './Preferences';
import { useWorkspace } from './Workspace';
import { Notice } from './shared';
import type { ProjectActionThread, ProjectNextAction } from './project-actions-model';
import '../styles/project-actions.css';

type EditMode = { kind: 'edit' | 'complete' | 'paused' | 'blocked' | 'delete' | 'delete-result'; revision: number; completionId?: string } | null;
type Mutation = (path: string, method: string, body: unknown, message: string) => Promise<boolean>;
const textField = (data: FormData, key: string) => String(data.get(key) ?? '').trim();

function ActionFields({ action, threads }: { action?: ProjectNextAction; threads: ProjectActionThread[] }) {
  const { t } = usePreferences();
  const [threadId, setThreadId] = useState(action?.thread?.id ?? threads[0]?.id ?? '');
  const title = useRef<HTMLInputElement>(null);
  const thread = threads.find(item => item.id === threadId);
  const oldThread = action?.thread && !threads.some(item => item.id === action.thread?.id) ? action.thread : null;
  return <>
    <label className="project-action-wide">{t('下一步要做什么', 'What is the next step?')}<input ref={title} name="title" required maxLength={200} defaultValue={action?.title ?? ''} placeholder={t('例如：做出花束游戏的第一屏交互', 'For example: build the bouquet game’s first interaction')}/></label>
    <label className="project-action-wide">{t('怎样才算完成', 'What counts as done?')}<textarea name="acceptance" required maxLength={2000} rows={2} defaultValue={action?.acceptance ?? ''} placeholder={t('写下可以检查的结果，例如：可选择三种花，组合后显示预览。', 'Describe a checkable result, e.g. choose three flowers and preview their arrangement.')}/></label>
    <label>{t('接着哪段对话做', 'Continue which conversation?')}<select name="threadId" value={threadId} onChange={event => setThreadId(event.target.value)}><option value="">{t('暂不关联对话', 'No conversation yet')}</option>{oldThread && <option value={oldThread.id}>{oldThread.title}{t('（已保存的关联）', ' (saved link)')}</option>}{threads.map(item => <option key={item.id} value={item.id}>{item.title}</option>)}</select></label>
    <label>{t('计划日期（可选）', 'Planned date (optional)')}<input name="dueDate" type="date" defaultValue={action?.dueDate ?? ''}/></label>
    {thread?.latest?.request && <details className="project-action-seed project-action-wide"><summary>{t('参考这段对话的最近要求', 'Review the latest request in this conversation')}</summary><p>{thread.latest.request}</p><button type="button" className="pw-text-button" onClick={() => { if (title.current) { title.current.value = thread.latest!.request.slice(0, 200); title.current.focus(); } }}>{t('填入标题，再由我修改', 'Use as a title, then edit')}</button><small>{t('这是原始要求，请调整成一个具体的下一步，并补充验收条件。', 'This is the original request. Refine it into one next step and add acceptance criteria.')}</small></details>}
  </>;
}

function ActionRow({ action, threads, path, mutate, busy, target }: { action: ProjectNextAction; threads: ProjectActionThread[]; path: string; mutate: Mutation; busy: boolean; target: boolean }) {
  const { t, locale } = usePreferences(); const [mode, setMode] = useState<EditMode>(null); const row = useRef<HTMLLIElement>(null); const form = useRef<HTMLFormElement>(null); const [localError, setLocalError] = useState('');
  useEffect(() => { if (target) { row.current?.focus(); row.current?.scrollIntoView?.({ block: 'center' }); } }, [target]);
  useEffect(() => { if (mode) form.current?.querySelector<HTMLElement>('input, textarea, button')?.focus(); }, [mode]);
  const begin = (kind: NonNullable<EditMode>['kind'], completionId?: string) => { setLocalError(''); setMode({ kind, revision: action.revision, completionId }); };
  const close = () => { setMode(null); row.current?.focus(); };
  const itemPath = `${path}/${encodeURIComponent(action.id)}`;
  const status = action.status === 'done' ? t('已完成', 'Completed') : action.status === 'blocked' ? t('遇到阻碍', 'Blocked') : action.status === 'paused' ? t('已暂停', 'Paused') : t('接着做', 'Next up');
  async function save(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!mode || busy) return; const data = new FormData(event.currentTarget); setLocalError('');
    let body: Record<string, unknown> = { revision: mode.revision }; let message = t('行动已更新。', 'Action updated.');
    if (mode.kind === 'edit') {
      const title = textField(data, 'title'), acceptance = textField(data, 'acceptance');
      if (!title || !acceptance) { setLocalError(t('请填写下一步和验收条件。', 'Add a next step and acceptance criteria.')); return; }
      const threadId = textField(data, 'threadId');
      body = { ...body, title, acceptance, dueDate: textField(data, 'dueDate') || null, ...(threadId === action.thread?.id ? {} : { threadId: threadId || null }) };
    } else if (mode.kind === 'complete') {
      const result = textField(data, 'result'); if (!result) { setLocalError(t('请留下这次完成的结果。', 'Record what you completed.')); return; }
      body = { ...body, status: 'done', result }; message = t('完成结果已保存，关联待办同步完成。可以继续安排下一步。', 'Result saved and any linked task completed. You can plan the next step.');
    } else if (mode.kind === 'delete') { body = { ...body, confirm: true }; message = t('已删除此行动，已有待办和外部项目保留。', 'Action deleted. Existing tasks and external projects are kept.'); }
    else if (mode.kind === 'delete-result') { body = { ...body, confirm: true }; message = t('仅删除了这次完成结果，行动状态、其他结果和已有待办保留。', 'Only this completion result was deleted. The action status, other results and existing tasks are kept.'); }
    else { const reason = textField(data, 'reason'); if (!reason) { setLocalError(t('请写下原因，方便下次接着做。', 'Leave a reason so you can pick up later.')); return; } body = { ...body, status: mode.kind, reason }; }
    const url = mode.kind === 'delete-result' ? `${itemPath}/completions/${encodeURIComponent(mode.completionId!)}` : itemPath;
    if (await mutate(url, mode.kind === 'delete' || mode.kind === 'delete-result' ? 'DELETE' : 'PATCH', body, message)) { if (mode.kind === 'complete' || mode.kind === 'delete') setMode(null); else close(); }
  }
  return <li ref={row} tabIndex={-1} className={`project-action-row is-${action.status}${target ? ' is-linked-target' : ''}`} data-action-id={action.id}>
    <div className="project-action-heading"><span className="project-action-status">{action.status === 'done' && <Check width={15}/>} {status}</span>{action.dueDate && <time dateTime={action.dueDate}>{t('计划 ', 'Planned ')}{action.dueDate}</time>}</div>
    <h4>{action.title}</h4><p className="project-action-acceptance"><strong>{t('完成标准', 'Done when')}</strong>{action.acceptance}</p>
    {action.reason && action.status !== 'done' && <p className="project-action-reason"><strong>{t('停在这里的原因', 'Why it is on hold')}</strong>{action.reason}</p>}
    {action.status === 'done' && <p className="project-action-result"><strong>{t('完成结果', 'Result')}</strong>{action.result || t('完成结果已删除', 'Completion result deleted')}{action.completedAt && <small>{dateLabel(action.completedAt, locale)}</small>}</p>}
    <div className="project-action-controls">
      {action.thread ? <a className="pw-button small primary" href={action.thread.url} title={action.thread.title}>{t('回到这段对话', 'Continue this conversation')}<ArrowRight width={16}/></a> : <span className="project-action-no-thread">{t('尚未关联对话，可在编辑中选择。', 'No conversation linked. Choose one when editing.')}</span>}
      {action.todoId ? <Link className="pw-text-button" to={`/todos?task=${encodeURIComponent(action.todoId)}`}>{t('查看关联待办', 'View linked task')}<ArrowRight width={14}/></Link> : action.status !== 'done' && <button className="pw-text-button" disabled={busy} onClick={() => void mutate(`${itemPath}/todo`, 'POST', {}, t('已加入待办，完成状态将与行动同步。', 'Added to tasks. Completion stays in sync with this action.'))}><Plus width={15}/>{t('加入待办', 'Add to tasks')}</button>}
      {action.status !== 'done' ? <button className="pw-button small" disabled={busy} onClick={() => begin('complete')}><Check width={16}/>{t('完成并记结果', 'Complete & record result')}</button> : <button className="pw-text-button" disabled={busy} onClick={() => void mutate(itemPath, 'PATCH', { status: 'active', revision: action.revision }, t('行动已重新打开，关联待办也已恢复，完成记录保留。', 'Action and linked task reopened. Completion records are kept.'))}>{t('重新打开', 'Reopen')}</button>}
    </div>
    <div className="project-action-secondary"><button className="pw-text-button" disabled={busy} onClick={() => begin('edit')}>{t('编辑行动', 'Edit action')}</button>{action.status !== 'done' && <>{action.status !== 'blocked' && <button className="pw-text-button" disabled={busy} onClick={() => begin('blocked')}>{t('遇到阻碍', 'Mark blocked')}</button>}{action.status !== 'paused' && <button className="pw-text-button" disabled={busy} onClick={() => begin('paused')}>{t('暂停', 'Pause')}</button>}{action.status !== 'active' && <button className="pw-text-button" disabled={busy} onClick={() => void mutate(itemPath, 'PATCH', { status: 'active', revision: action.revision }, t('已恢复，可以接着做。', 'Resumed. Ready to continue.'))}>{t('恢复行动', 'Resume action')}</button>}</>}<button className="pw-text-button idea-danger" disabled={busy} onClick={() => begin('delete')}>{t('删除行动', 'Delete action')}</button></div>
    {action.completions.length > 0 && <details className="project-action-completions"><summary>{t(`完成记录 · ${action.completions.length}`, `Completion records · ${action.completions.length}`)}</summary><ol>{action.completions.map(entry => <li key={entry.id}><time>{dateLabel(entry.completedAt, locale)}</time><p>{entry.result}</p><button className="pw-text-button idea-danger" disabled={busy} onClick={() => begin('delete-result', entry.id)}>{t('删除这次结果', 'Delete this result')}</button></li>)}</ol></details>}
    {mode && <form ref={form} className={`project-action-form${mode.kind.startsWith('delete') ? ' is-delete' : ''}`} onSubmit={event => void save(event)}>
      <h5 className="project-action-wide">{mode.kind === 'edit' ? t('修改下一步', 'Edit next step') : mode.kind === 'complete' ? t('留下结果，再接着往前走', 'Record the result before moving on') : mode.kind === 'delete' ? t('删除这条行动？', 'Delete this action?') : mode.kind === 'delete-result' ? t('删除这次完成结果？', 'Delete this completion result?') : mode.kind === 'blocked' ? t('记录当前阻碍', 'Record the blocker') : t('暂时放一放', 'Put this on hold')}</h5>
      {mode.kind === 'edit' ? <ActionFields action={action} threads={threads}/> : mode.kind === 'complete' ? <label className="project-action-wide">{t('这次完成了什么', 'What did you complete?')}<textarea name="result" required maxLength={4000} rows={3} placeholder={t('实际结果、验证方式，或下一步需要记住的事情…', 'The outcome, how you checked it, or what to remember next…')}/></label> : mode.kind === 'delete' ? <p className="project-action-wide">{t('只删除小院里的这条行动和它的完成记录。已有待办保留为独立记录，Codex 对话、项目文件和 GitHub 仓库都保留。此操作无法撤销。', 'Delete only this DailyHouse action and its completion records. Existing tasks remain as independent records. Codex conversations, project files and GitHub repositories stay. This cannot be undone.')}</p> : mode.kind === 'delete-result' ? <div className="project-action-wide project-result-delete"><blockquote>{action.completions.find(entry => entry.id === mode.completionId)?.result}</blockquote><p>{t('只删除以上这次结果，无法撤销。行动的完成状态、其他完成记录、已有待办、Codex 对话和外部项目保留。', 'Delete only the result above. This cannot be undone. The action’s completion status, other results, existing tasks, Codex conversations and external projects stay.')}</p></div> : <label className="project-action-wide">{t('原因', 'Reason')}<textarea name="reason" required maxLength={2000} rows={2} defaultValue={action.reason}/></label>}
      {localError && <p role="alert" className="project-action-wide project-action-error">{localError}</p>}
      {mode.revision !== action.revision && <div className="project-action-revision project-action-wide" role="status"><strong>{t('行动已在别处更新。请先核对最新记录：', 'This action changed elsewhere. Review the latest record first:')}</strong><dl><dt>{t('最新标题', 'Latest title')}</dt><dd>{action.title}</dd><dt>{t('最新完成标准', 'Latest acceptance criteria')}</dt><dd>{action.acceptance}</dd><dt>{t('最新状态与日期', 'Latest status and date')}</dt><dd>{status} · {action.dueDate || t('未安排日期', 'No planned date')}</dd>{action.thread && <><dt>{t('关联对话', 'Linked conversation')}</dt><dd>{action.thread.title}</dd></>}{action.reason && <><dt>{t('原因', 'Reason')}</dt><dd>{action.reason}</dd></>}{action.result && <><dt>{t('已保存结果', 'Saved result')}</dt><dd>{action.result}</dd></>}</dl><p>{t('你的输入仍然保留。核对后再保存，会用本次输入修改最新记录。', 'Your draft is kept. Saving after review will apply your inputs to the latest record.')}</p>{mode.kind === 'complete' && action.status === 'done' ? <p>{t('这条行动已完成，请取消本次操作查看结果。', 'This action is already complete. Cancel this operation to view its result.')}</p> : <button type="button" className="pw-button small" disabled={busy} onClick={() => setMode({ ...mode, revision: action.revision })}>{t('已核对最新记录，保留输入继续', 'Reviewed latest record; keep my draft')}</button>}</div>}
      <div className="project-action-form-buttons project-action-wide"><button className={`pw-button small ${mode.kind.startsWith('delete') ? 'idea-danger-button' : 'primary'}`} disabled={busy || mode.revision !== action.revision}>{busy ? t('保存中…', 'Saving…') : mode.kind === 'delete' ? t('确认删除行动', 'Confirm action deletion') : mode.kind === 'delete-result' ? t('确认删除这次结果', 'Confirm result deletion') : mode.kind === 'complete' ? t('保存结果并完成', 'Save result & complete') : t('保存行动', 'Save action')}</button><button type="button" className="pw-text-button" disabled={busy} onClick={close}>{t('取消', 'Cancel')}</button></div>
    </form>}
  </li>;
}

export default function ProjectNextActions({ projectId, projectTitle, threads, targetAction, refreshKey }: { projectId: string; projectTitle: string; threads: ProjectActionThread[]; targetAction?: string; refreshKey?: string }) {
  const { t, language } = usePreferences(); const { data, refresh } = useWorkspace(); const [items, setItems] = useState<ProjectNextAction[]>([]); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [create, setCreate] = useState(false); const [error, setError] = useState(''); const [feedback, setFeedback] = useState(''); const [doneOpen, setDoneOpen] = useState(false); const generation = useRef(0); const pending = useRef(false); const createRequestId = useRef(''); const createForm = useRef<HTMLFormElement>(null); const heading = useRef<HTMLHeadingElement>(null); const restoreFocus = useRef(false); const path = `/project-resume/${encodeURIComponent(projectId)}/actions`;
  const load = useCallback(async () => { const run = ++generation.current; try { const next = await request<{ items: ProjectNextAction[] }>(path); if (run === generation.current) setItems(next.items); } catch (err) { if (run === generation.current) setError((err as Error).message); } finally { if (run === generation.current) setLoading(false); } }, [path, language]);
  useEffect(() => { void load(); return () => { generation.current++; }; }, [load, data?.todos, refreshKey]);
  useEffect(() => { setError(''); setFeedback(''); }, [language]);
  useEffect(() => { if (create) createForm.current?.querySelector<HTMLInputElement>('input')?.focus(); }, [create]);
  useEffect(() => { if (restoreFocus.current) { heading.current?.focus(); restoreFocus.current = false; } }, [items]);
  useEffect(() => { if (targetAction && items.some(item => item.id === targetAction && item.status === 'done')) setDoneOpen(true); }, [items, targetAction]);
  const mutate: Mutation = async (url, method, body, message) => { if (pending.current) return false; pending.current = true; setBusy(true); setError(''); setFeedback(''); try { await request(url, method, body); restoreFocus.current = method === 'DELETE' || method === 'POST' || (body as { status?: string })?.status === 'done'; await load(); await refresh(); setFeedback(message); return true; } catch (err) { setError((err as Error).message); return false; } finally { pending.current = false; setBusy(false); } };
  async function add(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const formData = new FormData(event.currentTarget); const title = textField(formData, 'title'), acceptance = textField(formData, 'acceptance'); if (!title || !acceptance) { setError(t('请填写下一步和验收条件。', 'Add a next step and acceptance criteria.')); return; } const threadId = textField(formData, 'threadId'); if (await mutate(path, 'POST', { requestId: createRequestId.current, title, acceptance, ...(threadId ? { threadId } : {}), dueDate: textField(formData, 'dueDate') || null }, t('下一步已记好，可以回到对应对话开始。', 'Next step saved. Continue in its conversation when ready.'))) setCreate(false); }
  const active = items.filter(item => item.status !== 'done'), done = items.filter(item => item.status === 'done');
  const renderRow = (action: ProjectNextAction) => <ActionRow key={action.id} action={action} threads={threads} path={path} mutate={mutate} busy={busy} target={targetAction === action.id}/>;
  return <section className="project-next-actions" aria-label={t(`${projectTitle} 的下一步行动`, `Next actions for ${projectTitle}`)}><header><div><h3 ref={heading} tabIndex={-1}>{t('下一步行动', 'Next actions')}{active.length > 0 && <span>{active.length}</span>}</h3><p>{t('确定一个具体动作，留好完成标准，下次直接接着做。', 'Choose a concrete step and a clear finish line, ready for your next session.')}</p></div><button className="pw-button small primary" disabled={busy || create} onClick={() => { setError(''); createRequestId.current = crypto.randomUUID(); setCreate(true); }}><Plus width={16}/>{t('安排下一步', 'Plan next step')}</button></header>
    {error && <Notice error>{error} <button className="pw-text-button" disabled={busy || loading} onClick={() => { setError(''); void load(); }}>{t('重新读取行动', 'Reload actions')}</button></Notice>}{feedback && <Notice>{feedback}</Notice>}
    {!loading && !error && targetAction && !items.some(item => item.id === targetAction) && <Notice>{t('这条行动已删除或暂不可用。关联待办保留在今日待办中。', 'This action was deleted or is unavailable. Its linked task remains in your tasks.')}</Notice>}
    {create && <form ref={createForm} className="project-action-form" onSubmit={event => void add(event)}><ActionFields threads={threads}/><div className="project-action-form-buttons project-action-wide"><button className="pw-button small primary" disabled={busy}>{busy ? t('保存中…', 'Saving…') : t('保存下一步', 'Save next step')}</button><button type="button" className="pw-text-button" disabled={busy} onClick={() => { setCreate(false); heading.current?.focus(); }}>{t('取消', 'Cancel')}</button></div></form>}
    {loading ? <p className="project-action-empty" role="status">{t('正在读取下一步…', 'Loading next actions…')}</p> : active.length ? <ul className="project-action-list">{active.map(renderRow)}</ul> : !create && <p className="project-action-empty">{done.length ? t('这一轮的行动已完成。安排下一步，让项目继续往前。', 'This round is complete. Plan the next step to keep moving.') : t('还没有下一步。从一段对话里挑出一个能落地的动作，安排到待办。', 'No next step yet. Pick one concrete action from a conversation and add it to your tasks.')}</p>}
    {done.length > 0 && <div className="project-action-history"><button className="pw-text-button" aria-expanded={doneOpen} aria-controls={`action-history-${projectId}`} onClick={() => setDoneOpen(value => !value)}><Check width={16}/>{t(`已完成的行动 · ${done.length}`, `Completed actions · ${done.length}`)}<span aria-hidden="true">{doneOpen ? '−' : '+'}</span></button>{doneOpen && <ul id={`action-history-${projectId}`} className="project-action-list">{done.map(renderRow)}</ul>}</div>}
  </section>;
}
