import { useEffect, useState, type FormEvent } from 'react';
import { BookOpen, Calendar } from 'pixelarticons/react';
import { request, type Settings } from './api';
import { useWorkspace } from './Workspace';
import { usePreferences } from './Preferences';
import { Notice, PageHead } from './shared';
import LocalPathPicker from './LocalPathPicker';
import PrivateSync from './PrivateSync';
import DevelopmentTools from './DevelopmentTools';
export default function SettingsPage() {
  const { t } = usePreferences();
  const { data, refresh } = useWorkspace(); const [vaultPath, setVaultPath] = useState(''); const [calendarFile, setCalendarFile] = useState(''); const [calendarUrl, setCalendarUrl] = useState(''); const [calendarKind, setCalendarKind] = useState<'file' | 'url'>('file'); const [busy, setBusy] = useState(''); const [error, setError] = useState(''); const [saved, setSaved] = useState('');
  const [motion, setMotion] = useState(data?.settings.animationEnabled ?? true);
  useEffect(() => { setMotion(data?.settings.animationEnabled ?? true); }, [data?.settings.animationEnabled]);
  useEffect(() => { setVaultPath(data?.settings.vaultPath ?? ''); }, [data?.settings.vaultPath]);
  useEffect(() => { setCalendarFile(data?.settings.calendarFile ?? ''); }, [data?.settings.calendarFile]);
  useEffect(() => { setCalendarKind(data?.settings.calendarUrlConfigured ? 'url' : 'file'); }, [data?.settings.calendarUrlConfigured]);
  if (!data) return null;
  async function save(section: string, patch: Partial<Settings> & { calendarUrl?: string }) { setBusy(section); setError(''); setSaved(''); try { await request('/settings', 'PATCH', patch); await refresh(); if (section === 'calendar') setCalendarUrl(''); setSaved(section); } catch (err) { setError(err instanceof Error ? err.message : t('未能保存设置，请重试。', 'Could not save settings. Please try again.')); if (section === 'motion') setMotion(data?.settings.animationEnabled ?? true); } finally { setBusy(''); } }
  const vaultSubmit = (e: FormEvent) => { e.preventDefault(); void save('vault', { vaultPath: vaultPath.trim() }); };
  const calendarSubmit = (e: FormEvent) => { e.preventDefault(); if (calendarKind === 'file') void save('calendar', { calendarFile: calendarFile.trim(), calendarUrl: '' }); else if (!calendarUrl.trim() && !data.settings.calendarUrlConfigured) setError(t('请填写日历订阅地址，或选择已有的日历文件。', 'Enter a calendar subscription URL or choose a calendar file.')); else void save('calendar', { calendarFile: '', ...(calendarUrl.trim() ? { calendarUrl: calendarUrl.trim() } : {}) }); };
  return <div className="pw-page pw-settings"><PageHead title={t('小院设置', 'Garden settings')} description={t('只连接你用得上的来源。', 'Connect the sources you use.')}/>{error && <Notice error>{error}</Notice>}
    <section className="pw-setting-section"><div><span className="pw-inventory-icon"><BookOpen/></span><h2>{t('Obsidian 仓库', 'Obsidian vault')}</h2><p>{t('选择包含 .obsidian 文件夹的仓库根目录。', 'Choose the vault’s root folder, which contains a .obsidian folder.')}</p></div><form onSubmit={vaultSubmit}><LocalPathPicker kind="vault" label={t('仓库文件夹', 'Vault folder')} value={vaultPath} onChange={setVaultPath} onError={setError} onBusy={value => setBusy(value ? 'picker' : '')} disabled={!!busy}/><p className="pw-footnote">{t('连接后可阅读 Markdown 笔记和站内双链。', 'Read Markdown notes and follow links between them.')}</p><div className="pw-form-actions"><button className="pw-button primary" disabled={!!busy}>{busy === 'vault' ? t('保存中…', 'Saving…') : t('保存仓库', 'Save vault')}</button>{saved === 'vault' && <span role="status">{t('已保存', 'Saved')}</span>}</div></form></section>
    <section className="pw-setting-section"><div><span className="pw-inventory-icon"><Calendar/></span><h2>{t('日历来源', 'Calendar source')}</h2><p>{t('Windows 优先使用 Google Calendar；Mac 可继续使用 Apple Calendar。支持只读订阅或导出的 .ics 文件。', 'Use Google Calendar on Windows or Apple Calendar on Mac. Read a subscription or an exported .ics file.')}</p></div><form onSubmit={calendarSubmit}>
      <fieldset className="pw-radio-group"><legend>{t('读取方式', 'Connection method')}</legend><label><input type="radio" name="calendar-source" checked={calendarKind === 'file'} onChange={() => setCalendarKind('file')}/>{t('日历文件', 'Calendar file')}</label><label><input type="radio" name="calendar-source" checked={calendarKind === 'url'} onChange={() => setCalendarKind('url')}/>{t('订阅链接', 'Subscription URL')}</label></fieldset>
      {calendarKind === 'file' ? <LocalPathPicker kind="calendar" label={t('.ics 文件路径', '.ics file path')} value={calendarFile} onChange={setCalendarFile} onError={setError} onBusy={value => setBusy(value ? 'picker' : '')} disabled={!!busy} placeholder={t('选择 Google 或 Apple Calendar 导出的 .ics', 'Choose an .ics exported from Google or Apple Calendar')}/> : <label>{t('Google / iCloud 日历订阅链接', 'Google / iCloud calendar subscription URL')}<input type="password" autoComplete="new-password" value={calendarUrl} onChange={e => setCalendarUrl(e.target.value)} placeholder={data.settings.calendarUrlConfigured ? t('已有链接；留空则保留', 'URL saved; leave blank to keep it') : t('https:// 或 webcal:// …', 'https:// or webcal:// …')}/></label>}
      <p className="pw-footnote">{calendarKind === 'file' ? t('Google Calendar：设置 → 导入和导出 → 导出，解压后选择其中一个 .ics。文件是快照；更新文件后点击“读取日历”。', 'Google Calendar: Settings → Import & export → Export. Unzip and choose an .ics file. Files are snapshots; refresh after replacing the file.') : t('Google Calendar：设置 → 选择日历 → 集成日历 → iCal 格式的私密地址。链接只保存在本机；之后读取即可获取来源更新。Apple 可使用已有 iCloud 订阅。', 'Google Calendar: Settings → select calendar → Integrate calendar → Secret address in iCal format. The link stays on this computer; refresh to read source updates. Existing iCloud subscriptions also work.')}</p>
      <p className="pw-footnote">{t('显示今天起 180 天的安排，可在待办页按月份查看。', 'Shows the next 180 days, with a month selector on the Tasks page.')}</p>
      <div className="pw-form-actions"><button className="pw-button primary" disabled={!!busy}>{busy === 'calendar' ? t('保存中…', 'Saving…') : t('保存日历来源', 'Save calendar source')}</button>{data.settings.calendarConfigured && <button type="button" className="pw-text-button" disabled={!!busy} onClick={() => void save('calendar', { calendarFile: '', calendarUrl: '' })}>{t('断开来源', 'Disconnect source')}</button>}{saved === 'calendar' && <span role="status">{t('已保存，去待办页读取日历', 'Saved. Load the calendar on the Tasks page.')}</span>}</div>
    </form></section>
    <section className="pw-setting-section"><div><h2>{t('小院动态', 'Garden motion')}</h2><p>{t('园丁和植物的轻量动画。', 'Gentle animation for the gardener and plants.')}</p></div><label className="pw-toggle"><input type="checkbox" checked={motion} disabled={!!busy} onChange={e => { setMotion(e.target.checked); void save('motion', { animationEnabled: e.target.checked }); }}/><span>{t('开启小院动画', 'Enable garden animation')}<small>{t('也会遵循系统的“减少动态效果”设置。', 'Also respects your system’s reduced motion setting.')}</small></span></label></section>
    <PrivateSync/>
    <DevelopmentTools/>
  </div>;
}
