import { useEffect, useState, type FormEvent } from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, BookOpen, Calendar, Folder } from 'pixelarticons/react';
import { request, type Settings } from './api';
import { useWorkspace } from './Workspace';
import { Notice, PageHead } from './shared';
export default function SettingsPage() {
  const { data, refresh } = useWorkspace(); const [vaultPath, setVaultPath] = useState(''); const [calendarFile, setCalendarFile] = useState(''); const [calendarUrl, setCalendarUrl] = useState(''); const [calendarKind, setCalendarKind] = useState<'file' | 'url'>('file'); const [busy, setBusy] = useState(''); const [error, setError] = useState(''); const [saved, setSaved] = useState('');
  const [motion, setMotion] = useState(data?.settings.animationEnabled ?? true);
  useEffect(() => { setMotion(data?.settings.animationEnabled ?? true); }, [data?.settings.animationEnabled]);
  useEffect(() => { setVaultPath(data?.settings.vaultPath ?? ''); }, [data?.settings.vaultPath]);
  useEffect(() => { setCalendarFile(data?.settings.calendarFile ?? ''); }, [data?.settings.calendarFile]);
  useEffect(() => { setCalendarKind(data?.settings.calendarUrlConfigured ? 'url' : 'file'); }, [data?.settings.calendarUrlConfigured]);
  if (!data) return null;
  async function save(section: string, patch: Partial<Settings> & { calendarUrl?: string }) { setBusy(section); setError(''); setSaved(''); try { await request('/settings', 'PATCH', patch); await refresh(); if (section === 'calendar') setCalendarUrl(''); setSaved(section); } catch (err) { setError((err as Error).message); if (section === 'motion') setMotion(data?.settings.animationEnabled ?? true); } finally { setBusy(''); } }
  const vaultSubmit = (e: FormEvent) => { e.preventDefault(); void save('vault', { vaultPath: vaultPath.trim() }); };
  const calendarSubmit = (e: FormEvent) => { e.preventDefault(); if (calendarKind === 'file') void save('calendar', { calendarFile: calendarFile.trim(), calendarUrl: '' }); else void save('calendar', { calendarFile: '', ...(calendarUrl.trim() ? { calendarUrl: calendarUrl.trim() } : {}) }); };
  return <div className="pw-page pw-settings"><PageHead title="小院设置" description="只连接你用得上的来源。"/>{error && <Notice error>{error}</Notice>}
    <section className="pw-setting-section"><div><span className="pw-inventory-icon"><BookOpen/></span><h2>Obsidian 仓库</h2><p>选择包含 .obsidian 文件夹的仓库根目录。</p></div><form onSubmit={vaultSubmit}><label>仓库文件夹<input value={vaultPath} onChange={e => setVaultPath(e.target.value)} placeholder="例如 C:\Users\AlexS\Documents\我的笔记" spellCheck={false}/></label><p className="pw-footnote">连接后可阅读 Markdown 笔记和站内双链。</p><div className="pw-form-actions"><button className="pw-button primary" disabled={!!busy}>{busy === 'vault' ? '保存中…' : '保存仓库'}</button>{saved === 'vault' && <span role="status">已保存</span>}</div></form></section>
    <section className="pw-setting-section"><div><span className="pw-inventory-icon"><Calendar/></span><h2>Apple Calendar</h2><p>在这台 Windows 电脑上，通过日历文件或已有订阅读取。</p></div><form onSubmit={calendarSubmit}><fieldset className="pw-radio-group"><legend>读取来源</legend><label><input type="radio" name="calendar-source" checked={calendarKind === 'file'} onChange={() => setCalendarKind('file')}/>日历文件</label><label><input type="radio" name="calendar-source" checked={calendarKind === 'url'} onChange={() => setCalendarKind('url')}/>已有订阅链接</label></fieldset>{calendarKind === 'file' ? <label>.ics 文件路径<input value={calendarFile} onChange={e => setCalendarFile(e.target.value)} placeholder="填写从 Apple Calendar 导出的 .ics 文件路径" spellCheck={false}/></label> : <label>iCloud 日历订阅链接<input type="password" autoComplete="new-password" value={calendarUrl} onChange={e => setCalendarUrl(e.target.value)} placeholder={data.settings.calendarUrlConfigured ? '已有链接；留空则保留' : 'https:// 或 webcal:// …'}/></label>}<p className="pw-footnote">{calendarKind === 'file' ? '文件更新后，在待办页点击“读取日历”。' : '使用你已有的订阅地址，链接只保存在本机。'}</p><div className="pw-form-actions"><button className="pw-button primary" disabled={!!busy}>{busy === 'calendar' ? '保存中…' : '保存日历来源'}</button>{data.settings.calendarConfigured && <button type="button" className="pw-text-button" disabled={!!busy} onClick={() => void save('calendar', { calendarFile: '', calendarUrl: '' })}>断开来源</button>}{saved === 'calendar' && <span role="status">已保存，去待办页读取日历</span>}</div></form></section>
    <section className="pw-setting-section"><div><span className="pw-inventory-icon"><Folder/></span><h2>桌面读取</h2><p>从熟悉的桌面，拾起下一件事。</p></div><div><p className="pw-path">{data.settings.desktopPath}</p><p className="pw-footnote">手动读取文件名、类型与修改时间。需要处理的文件，可在待办页逐个加入。</p><Link className="pw-text-button" to="/todos">去读取桌面 <ArrowRight width={17}/></Link></div></section>
    <section className="pw-setting-section"><div><h2>小院动态</h2><p>园丁和植物的轻量动画。</p></div><label className="pw-toggle"><input type="checkbox" checked={motion} disabled={!!busy} onChange={e => { setMotion(e.target.checked); void save('motion', { animationEnabled: e.target.checked }); }}/><span>开启小院动画<small>也会遵循系统的“减少动态效果”设置。</small></span></label></section>
    <section className="pw-setting-section"><div><h2>Chase 连接</h2></div><div><p>尚待确认原来绑定的应用或服务。</p><Link className="pw-text-button" to="/finance">查看账本 <ArrowRight width={17}/></Link></div></section>
  </div>;
}
