import { useEffect, useState, type FormEvent } from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, BookOpen, Calendar, Folder } from 'pixelarticons/react';
import { request, type Settings } from './api';
import { useWorkspace } from './Workspace';
import { usePreferences } from './Preferences';
import { Notice, PageHead } from './shared';
export default function SettingsPage() {
  const { t } = usePreferences();
  const { data, refresh } = useWorkspace(); const [vaultPath, setVaultPath] = useState(''); const [calendarFile, setCalendarFile] = useState(''); const [calendarUrl, setCalendarUrl] = useState(''); const [calendarKind, setCalendarKind] = useState<'file' | 'url'>('file'); const [busy, setBusy] = useState(''); const [error, setError] = useState(''); const [saved, setSaved] = useState('');
  const [motion, setMotion] = useState(data?.settings.animationEnabled ?? true);
  useEffect(() => { setMotion(data?.settings.animationEnabled ?? true); }, [data?.settings.animationEnabled]);
  useEffect(() => { setVaultPath(data?.settings.vaultPath ?? ''); }, [data?.settings.vaultPath]);
  useEffect(() => { setCalendarFile(data?.settings.calendarFile ?? ''); }, [data?.settings.calendarFile]);
  useEffect(() => { setCalendarKind(data?.settings.calendarUrlConfigured ? 'url' : 'file'); }, [data?.settings.calendarUrlConfigured]);
  if (!data) return null;
  async function save(section: string, patch: Partial<Settings> & { calendarUrl?: string }) { setBusy(section); setError(''); setSaved(''); try { await request('/settings', 'PATCH', patch); await refresh(); if (section === 'calendar') setCalendarUrl(''); setSaved(section); } catch (err) { setError(err instanceof Error ? err.message : t('未能保存设置，请重试。', 'Could not save settings. Please try again.')); if (section === 'motion') setMotion(data?.settings.animationEnabled ?? true); } finally { setBusy(''); } }
  const vaultSubmit = (e: FormEvent) => { e.preventDefault(); void save('vault', { vaultPath: vaultPath.trim() }); };
  const calendarSubmit = (e: FormEvent) => { e.preventDefault(); if (calendarKind === 'file') void save('calendar', { calendarFile: calendarFile.trim(), calendarUrl: '' }); else void save('calendar', { calendarFile: '', ...(calendarUrl.trim() ? { calendarUrl: calendarUrl.trim() } : {}) }); };
  return <div className="pw-page pw-settings"><PageHead title={t('小院设置', 'Garden settings')} description={t('只连接你用得上的来源。', 'Connect the sources you use.')}/>{error && <Notice error>{error}</Notice>}
    <section className="pw-setting-section"><div><span className="pw-inventory-icon"><BookOpen/></span><h2>{t('Obsidian 仓库', 'Obsidian vault')}</h2><p>{t('选择包含 .obsidian 文件夹的仓库根目录。', 'Choose the vault’s root folder, which contains a .obsidian folder.')}</p></div><form onSubmit={vaultSubmit}><label>{t('仓库文件夹', 'Vault folder')}<input value={vaultPath} onChange={e => setVaultPath(e.target.value)} placeholder={t('例如 C:\\Users\\AlexS\\Documents\\我的笔记', 'e.g. C:\\Users\\AlexS\\Documents\\My Notes')} spellCheck={false}/></label><p className="pw-footnote">{t('连接后可阅读 Markdown 笔记和站内双链。', 'Read Markdown notes and follow links between them.')}</p><div className="pw-form-actions"><button className="pw-button primary" disabled={!!busy}>{busy === 'vault' ? t('保存中…', 'Saving…') : t('保存仓库', 'Save vault')}</button>{saved === 'vault' && <span role="status">{t('已保存', 'Saved')}</span>}</div></form></section>
    <section className="pw-setting-section"><div><span className="pw-inventory-icon"><Calendar/></span><h2>Apple Calendar</h2><p>{t('在这台 Windows 电脑上，通过日历文件或已有订阅读取。', 'On this Windows computer, load a calendar file or an existing subscription.')}</p></div><form onSubmit={calendarSubmit}><fieldset className="pw-radio-group"><legend>{t('读取来源', 'Calendar source')}</legend><label><input type="radio" name="calendar-source" checked={calendarKind === 'file'} onChange={() => setCalendarKind('file')}/>{t('日历文件', 'Calendar file')}</label><label><input type="radio" name="calendar-source" checked={calendarKind === 'url'} onChange={() => setCalendarKind('url')}/>{t('已有订阅链接', 'Existing subscription')}</label></fieldset>{calendarKind === 'file' ? <label>{t('.ics 文件路径', '.ics file path')}<input value={calendarFile} onChange={e => setCalendarFile(e.target.value)} placeholder={t('填写从 Apple Calendar 导出的 .ics 文件路径', 'Path to a .ics file exported from Apple Calendar')} spellCheck={false}/></label> : <label>{t('iCloud 日历订阅链接', 'iCloud calendar subscription URL')}<input type="password" autoComplete="new-password" value={calendarUrl} onChange={e => setCalendarUrl(e.target.value)} placeholder={data.settings.calendarUrlConfigured ? t('已有链接；留空则保留', 'URL saved; leave blank to keep it') : t('https:// 或 webcal:// …', 'https:// or webcal:// …')}/></label>}<p className="pw-footnote">{calendarKind === 'file' ? t('文件更新后，在待办页点击“读取日历”。', 'After the file changes, select “Load calendar” on the Tasks page.') : t('使用你已有的订阅地址，链接只保存在本机。', 'Use an existing subscription URL. It is stored only on this computer.')}</p><div className="pw-form-actions"><button className="pw-button primary" disabled={!!busy}>{busy === 'calendar' ? t('保存中…', 'Saving…') : t('保存日历来源', 'Save calendar source')}</button>{data.settings.calendarConfigured && <button type="button" className="pw-text-button" disabled={!!busy} onClick={() => void save('calendar', { calendarFile: '', calendarUrl: '' })}>{t('断开来源', 'Disconnect source')}</button>}{saved === 'calendar' && <span role="status">{t('已保存，去待办页读取日历', 'Saved. Load the calendar on the Tasks page.')}</span>}</div></form></section>
    <section className="pw-setting-section"><div><span className="pw-inventory-icon"><Folder/></span><h2>{t('桌面读取', 'Desktop files')}</h2><p>{t('从熟悉的桌面，拾起下一件事。', 'Find your next task among the files on your desktop.')}</p></div><div><p className="pw-path">{data.settings.desktopPath}</p><p className="pw-footnote">{t('手动读取文件名、类型与修改时间。需要处理的文件，可在待办页逐个加入。', 'Browse file names, types and modified dates when you choose. Add files to your tasks one at a time.')}</p><Link className="pw-text-button" to="/todos">{t('去读取桌面', 'Browse desktop files')} <ArrowRight width={17}/></Link></div></section>
    <section className="pw-setting-section"><div><h2>{t('小院动态', 'Garden motion')}</h2><p>{t('园丁和植物的轻量动画。', 'Gentle animation for the gardener and plants.')}</p></div><label className="pw-toggle"><input type="checkbox" checked={motion} disabled={!!busy} onChange={e => { setMotion(e.target.checked); void save('motion', { animationEnabled: e.target.checked }); }}/><span>{t('开启小院动画', 'Enable garden animation')}<small>{t('也会遵循系统的“减少动态效果”设置。', 'Also respects your system’s reduced motion setting.')}</small></span></label></section>
    <section className="pw-setting-section"><div><h2>{t('Chase 连接', 'Chase connection')}</h2></div><div><p>{t('尚待确认原来绑定的应用或服务。', 'We still need to confirm the app or service you originally used.')}</p><Link className="pw-text-button" to="/finance">{t('查看账本', 'View ledger')} <ArrowRight width={17}/></Link></div></section>
  </div>;
}
