import { useState, type ReactNode, type FormEvent } from 'react';
import { Plus, Check, Close } from 'pixelarticons/react';
import { localDay, request, type Todo } from './api';
import { useWorkspace } from './Workspace';
export function PageHead({ title, description, children }: { title: string; description: string; children?: ReactNode }) { return <header className="pw-page-head"><div><h1>{title}</h1><p>{description}</p></div>{children}</header>; }
export function Notice({ children, error = false }: { children: ReactNode; error?: boolean }) { return <p className={`pw-notice${error ? ' is-error' : ''}`} role={error ? 'alert' : 'status'}>{children}</p>; }
export function Empty({ title, children }: { title: string; children?: ReactNode }) { return <div className="pw-empty"><span className="pw-sprout" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M11 21V11H7V9H3V3h6v2h3v4h1V7h3V5h5v6h-3v2h-5v8z" fill="currentColor"/><path d="M7 22h10v2H7z" fill="#9a7345"/></svg></span><h3>{title}</h3>{children && <div>{children}</div>}</div>; }
export function AddTodo({ compact = false }: { compact?: boolean }) {
  const { refresh } = useWorkspace(); const [title, setTitle] = useState(''); const [dueDate, setDueDate] = useState(localDay()); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('');
  async function submit(event: FormEvent) { event.preventDefault(); if (!title.trim() || busy) return; setBusy(true); setMessage(''); try { await request('/todos', 'POST', { title: title.trim(), dueDate: dueDate || null }); setTitle(''); await refresh(); } catch (err) { setMessage((err as Error).message); } finally { setBusy(false); } }
  return <><form className={`pw-add${compact ? ' is-compact' : ''}`} onSubmit={submit}><label className="pw-grow"><span className="pw-sr-only">待办事项</span><input aria-label="待办事项" placeholder="记下一件想完成的小事…" value={title} onChange={e => setTitle(e.target.value)} maxLength={180} required /></label>{!compact && <label className="pw-due"><span className="pw-sr-only">计划日期</span><input aria-label="计划日期" type="date" value={dueDate} onChange={e => setDueDate(e.target.value)} /></label>}<button className="pw-button primary" type="submit" disabled={busy || !title.trim()}><Plus width={18} height={18}/>{busy ? '添加中…' : '添加待办'}</button></form>{message && <Notice error>{message}</Notice>}</>;
}
export function TodoRows({ items, allowDelete = false }: { items: Todo[]; allowDelete?: boolean }) {
  const { refresh } = useWorkspace(); const [busy, setBusy] = useState(''); const [error, setError] = useState('');
  async function change(todo: Todo, remove = false) { if (busy) return; setBusy(todo.id); setError(''); try { await request(`/todos/${encodeURIComponent(todo.id)}`, remove ? 'DELETE' : 'PATCH', remove ? undefined : { done: !todo.done }); await refresh(); } catch (err) { setError((err as Error).message); } finally { setBusy(''); } }
  return <>{error && <Notice error>{error}</Notice>}<ul className="pw-todos">{items.map(todo => <li key={todo.id} className={todo.done ? 'is-done' : ''}><button className="pw-check" aria-label={`${todo.done ? '恢复' : '完成'}：${todo.title}`} aria-pressed={todo.done} disabled={!!busy} onClick={() => void change(todo)}>{todo.done && <Check width={17} height={17}/>}</button><div className="pw-grow"><span className="pw-task-title">{todo.title}</span><small>{todo.dueDate ? `${todo.dueDate}${!todo.done && todo.dueDate < localDay() ? ' · 待补上' : ''}` : '未设日期'}</small></div>{allowDelete && <button className="pw-icon-button" aria-label={`删除：${todo.title}`} title="删除待办" disabled={!!busy} onClick={() => void change(todo, true)}><Close width={17} height={17}/></button>}</li>)}</ul></>;
}
