import { useState } from 'react';
import { Link } from 'react-router-dom';
import { Calendar, Folder, ArrowRight, Check } from 'pixelarticons/react';
import { dateLabel, localDay, request } from './api';
import { useWorkspace } from './Workspace';
import { usePreferences } from './Preferences';
import { AddTodo, Empty, Notice, PageHead, TodoRows } from './shared';
export default function TodosPage() {
  const { data, refresh } = useWorkspace();
  const { t, locale } = usePreferences();
  const [filter, setFilter] = useState<'today' | 'all' | 'done'>('today'); const [busy, setBusy] = useState(''); const [error, setError] = useState(''); const [added, setAdded] = useState<string[]>([]);
  if (!data) return null;
  const tasks = data.todos.filter(t => filter === 'done' ? t.done : !t.done && (filter === 'all' || !t.dueDate || t.dueDate <= localDay()));
  async function action(name: string, path: string, body?: unknown) { setBusy(name); setError(''); try { await request(path, 'POST', body); await refresh(); if (name.startsWith('file:')) setAdded(old => [...old, name.slice(5)]); } catch (err) { setError(err instanceof Error ? err.message : t('操作未完成，请重试。', 'The action could not be completed. Please try again.')); } finally { setBusy(''); } }
  return <div className="pw-page"><PageHead title={t('今日待办', 'Today’s tasks')} description={t('手动记一笔，读一读日历，再看看桌面。', 'Jot down a task, check your calendar and browse your desktop.')}/><section className="pw-paper pw-task-panel"><AddTodo/><div className="pw-tabs" aria-label={t('待办筛选', 'Filter tasks')}>{([['today', t('今天与未完成', 'Today & overdue')], ['all', t('全部待办', 'All tasks')], ['done', t('已完成', 'Completed')]] as const).map(([key, label]) => <button key={key} className={filter === key ? 'active' : ''} aria-pressed={filter === key} onClick={() => setFilter(key)}>{label}</button>)}</div>{tasks.length ? <TodoRows items={tasks} allowDelete/> : <Empty title={filter === 'done' ? t('完成的小事，会留在这里', 'A place for what you’ve finished') : t('这一页，暂时留白', 'A little room to begin')}><p>{filter === 'done' ? t('回到待办，完成一件再来看看。', 'Complete a task and you’ll find it here.') : t('在上方添加待办，或从桌面文件里挑一件。', 'Add a task above, or choose a file from your desktop.')}</p></Empty>}</section>
    {error && <Notice error>{error}</Notice>}<div className="pw-sources-grid"><section className="pw-paper"><div className="pw-section-head"><h2><Calendar/>Apple Calendar</h2><button className="pw-button small" disabled={!!busy || !data.settings.calendarConfigured} onClick={() => void action('calendar', '/calendar/refresh')}>{busy === 'calendar' ? t('读取中…', 'Loading…') : t('读取日历', 'Load calendar')}</button></div><p className="pw-subtle">{t('只读日程', 'Read-only events')} · {dateLabel(data.calendar.updatedAt, locale)}</p>{data.calendar.status !== 'ready' ? <Empty title={t('把日历带进小院', 'Bring your calendar into the garden')}><p>{data.calendar.message || t('在设置中指定 Apple Calendar 来源。', 'Choose an Apple Calendar source in Settings.')}</p><Link className="pw-text-button" to="/settings">{t('设置日历来源', 'Set up calendar')} <ArrowRight width={16}/></Link></Empty> : data.calendar.events.length ? <ul className="pw-events">{data.calendar.events.map(event => <li key={event.id}><time>{event.allDay ? `${event.start.slice(5, 10)} ${t('全天', 'All day')}` : dateLabel(event.start, locale)}</time><div><strong>{event.title}</strong>{event.location && <small>{event.location}</small>}</div></li>)}</ul> : <Empty title={t('近期没有日程', 'No upcoming events')}><p>{t('已读取的日历中，近期没有安排。', 'There are no upcoming events in the calendar you loaded.')}</p></Empty>}</section>
    <section className="pw-paper"><div className="pw-section-head"><h2><Folder/>{t('桌面拾遗', 'From your desktop')}</h2><button className="pw-button small" disabled={!!busy} onClick={() => void action('desktop', '/desktop/scan')}>{busy === 'desktop' ? t('读取中…', 'Loading…') : t('读取桌面', 'Browse desktop')}</button></div><p className="pw-subtle">{t('查看文件名与更新时间', 'File names and modified dates')} · {dateLabel(data.desktop.scannedAt, locale)}</p>{data.desktop.message && <p className="pw-footnote">{data.desktop.message}</p>}{data.desktop.files.length ? <ul className="pw-files">{data.desktop.files.map(file => <li key={file.id}><span className="pw-file-type">{file.extension?.replace('.', '').slice(0, 4).toUpperCase() || 'FILE'}</span><div className="pw-grow"><strong title={file.relativePath}>{file.name}</strong><small>{file.relativePath} · {dateLabel(file.modifiedAt, locale)}</small></div><button className="pw-button small" disabled={!!busy || added.includes(file.id)} aria-label={`${added.includes(file.id) ? t('已加入待办', 'Added to tasks') : t('加入待办', 'Add to tasks')}: ${file.name}`} onClick={() => void action(`file:${file.id}`, '/todos', { title: `${t('处理', 'Work on')}: ${file.name}`, dueDate: localDay() })}>{added.includes(file.id) ? <Check width={16}/> : t('加入待办', 'Add task')}</button></li>)}</ul> : <Empty title={t('桌面上，也许藏着下一步', 'Your next step might be on your desktop')}><p>{t('点击读取桌面，再决定哪些文件值得加入待办。', 'Browse your desktop, then choose which files to add as tasks.')}</p></Empty>}</section></div>
  </div>;
}
