import { useState } from 'react';
import { Link } from 'react-router-dom';
import { Calendar, Folder, ArrowRight, Check } from 'pixelarticons/react';
import { dateLabel, localDay, request } from './api';
import { useWorkspace } from './Workspace';
import { AddTodo, Empty, Notice, PageHead, TodoRows } from './shared';
export default function TodosPage() {
  const { data, refresh } = useWorkspace();
  const [filter, setFilter] = useState<'today' | 'all' | 'done'>('today'); const [busy, setBusy] = useState(''); const [error, setError] = useState(''); const [added, setAdded] = useState<string[]>([]);
  if (!data) return null;
  const tasks = data.todos.filter(t => filter === 'done' ? t.done : !t.done && (filter === 'all' || !t.dueDate || t.dueDate <= localDay()));
  async function action(name: string, path: string, body?: unknown) { setBusy(name); setError(''); try { await request(path, 'POST', body); await refresh(); if (name.startsWith('file:')) setAdded(old => [...old, name.slice(5)]); } catch (err) { setError((err as Error).message); } finally { setBusy(''); } }
  return <div className="pw-page"><PageHead title="今日待办" description="手动记一笔，读一读日历，再看看桌面。"/><section className="pw-paper pw-task-panel"><AddTodo/><div className="pw-tabs" aria-label="待办筛选">{([['today', '今天与未完成'], ['all', '全部待办'], ['done', '已完成']] as const).map(([key, label]) => <button key={key} className={filter === key ? 'active' : ''} aria-pressed={filter === key} onClick={() => setFilter(key)}>{label}</button>)}</div>{tasks.length ? <TodoRows items={tasks} allowDelete/> : <Empty title={filter === 'done' ? '完成的小事，会留在这里' : '这一页，暂时留白'}><p>{filter === 'done' ? '回到待办，完成一件再来看看。' : '在上方添加待办，或从桌面文件里挑一件。'}</p></Empty>}</section>
    {error && <Notice error>{error}</Notice>}<div className="pw-sources-grid"><section className="pw-paper"><div className="pw-section-head"><h2><Calendar/>Apple Calendar</h2><button className="pw-button small" disabled={!!busy || !data.settings.calendarConfigured} onClick={() => void action('calendar', '/calendar/refresh')}>{busy === 'calendar' ? '读取中…' : '读取日历'}</button></div><p className="pw-subtle">只读日程 · {dateLabel(data.calendar.updatedAt)}</p>{data.calendar.status !== 'ready' ? <Empty title="把日历带进小院"><p>{data.calendar.message || '在设置中指定 Apple Calendar 来源。'}</p><Link className="pw-text-button" to="/settings">设置日历来源 <ArrowRight width={16}/></Link></Empty> : data.calendar.events.length ? <ul className="pw-events">{data.calendar.events.map(event => <li key={event.id}><time>{event.allDay ? `${event.start.slice(5, 10)} 全天` : dateLabel(event.start)}</time><div><strong>{event.title}</strong>{event.location && <small>{event.location}</small>}</div></li>)}</ul> : <Empty title="近期没有日程"><p>已读取的日历中，近期没有安排。</p></Empty>}</section>
    <section className="pw-paper"><div className="pw-section-head"><h2><Folder/>桌面拾遗</h2><button className="pw-button small" disabled={!!busy} onClick={() => void action('desktop', '/desktop/scan')}>{busy === 'desktop' ? '读取中…' : '读取桌面'}</button></div><p className="pw-subtle">查看文件名与更新时间 · {dateLabel(data.desktop.scannedAt)}</p>{data.desktop.message && <p className="pw-footnote">{data.desktop.message}</p>}{data.desktop.files.length ? <ul className="pw-files">{data.desktop.files.map(file => <li key={file.id}><span className="pw-file-type">{file.extension?.replace('.', '').slice(0, 4).toUpperCase() || 'FILE'}</span><div className="pw-grow"><strong title={file.relativePath}>{file.name}</strong><small>{file.relativePath} · {dateLabel(file.modifiedAt)}</small></div><button className="pw-button small" disabled={!!busy || added.includes(file.id)} aria-label={`加入待办：${file.name}`} onClick={() => void action(`file:${file.id}`, '/todos', { title: `处理：${file.name}`, dueDate: localDay() })}>{added.includes(file.id) ? <Check width={16}/> : '加入待办'}</button></li>)}</ul> : <Empty title="桌面上，也许藏着下一步"><p>点击读取桌面，再决定哪些文件值得加入待办。</p></Empty>}</section></div>
  </div>;
}
